// This file was automatically generated by informer-gen

package etcd

import (
	v1beta2 "github.com/kubermatic/kubermatic/api/pkg/crd/client/seed/informers/externalversions/etcd/v1beta2"
	internalinterfaces "github.com/kubermatic/kubermatic/api/pkg/crd/client/seed/informers/externalversions/internalinterfaces"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1beta2 provides access to shared informers for resources in V1beta2.
	V1beta2() v1beta2.Interface
}

type group struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &group{f}
}

// V1beta2 returns a new v1beta2.Interface.
func (g *group) V1beta2() v1beta2.Interface {
	return v1beta2.New(g.SharedInformerFactory)
}
