{
 "title": "Controller Manager",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_bucket,controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Reconcile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reconciliations / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{controller=~\"$controller\"}[5m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=~\"$controller\"}[5m]))",
     "legendFormat": "Reconciles"
    }
   ]
  },
  {
   "title": "Controller Reconcile Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=~\"$controller\"}[1m])) by (le, controller))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket{controller=~\"$controller\"}[1m])) by (le, controller))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{controller=~\"$controller\"}[1m])) / sum(rate(controller_runtime_reconcile_time_seconds_count{controller=~\"$controller\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workqueue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workqueue Rate",
   "type": "timeseries",
   "description": "This metric measures the number of additions handled by the workqueue. A high value might indicate problems in the cluster, or in some of the nodes. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{name=~\"$controller\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Depth",
   "type": "timeseries",
   "description": "his metric enables you to verify how big the workqueue is. How many actions in the workqueue are waiting to be processed? It should remain a low value. The following query will allow you to easily see the increase rate in the kube-controller-manager queue. The bigger the workqueue is, the more has to process. Thus, a workqueue growing trend may indicate problems in your Kubernetes cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{mame=~\"$controller\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workqueue Latency",
   "type": "timeseries",
   "description": "The time that kube-controller-manager is taking to fulfill the different actions to keep the desired status of the cluster. ",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.7, sum(rate(workqueue_queue_duration_seconds_bucket{name=~\"$controller\"}[5m])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}