{
 "title": "Event Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Events count (Seed cluster)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({clusterID=\"seed\"} [1d])"
    }
   ]
  },
  {
   "title": "Events count aggregated (Seed cluster)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(clusterID) ( count_over_time({clusterID=\"seed\"} [1d]) )"
    }
   ]
  },
  {
   "title": "Events count (User clusters)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(clusterID) (count_over_time({clusterID!=\"seed\",seed=\"europe-west3-c\"} [1d]))"
    }
   ]
  },
  {
   "title": "Events share by projects (User clusters)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(projectID) (count_over_time({clusterID!=\"seed\",seed=\"europe-west3-c\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Event reason = Pulled (Seed cluster) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by( seed ) ( count_over_time ( { clusterID = \"seed\" } | json | line_format `{{.reason}}` |= \"Pulled\" [1h]  )) "
    }
   ]
  },
  {
   "title": "Event reason logs (Seed cluster) ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{ clusterID != \"seed\", seed=\"europe-west3-c\" } | json | line_format `clusterID --> {{.clusterID}}, reason --> {{.reason}}` "
    }
   ]
  },
  {
   "title": "Event reason = MachineDeploymentCreated (Seed cluster) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by( seed ) ( count_over_time ( { clusterID = \"seed\" } | json | line_format `{{.reason}}` |= \"MachineDeploymentCreated\" [1h]  )) "
    }
   ]
  }
 ]
}