{
 "title": "Nodeport Proxy",
 "description": "Envoy proxy monitoring Dashboard with cluster and service level templates. ",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubermatic_cluster_info,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Live servers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{app_kubernetes_io_name=\"nodeport-proxy-envoy\"})"
    }
   ]
  },
  {
   "title": "Avg uptime per node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{app_kubernetes_io_name=\"nodeport-proxy-envoy\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_allocated{app_kubernetes_io_name=\"nodeport-proxy-envoy\"})"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "SUM(envoy_server_memory_heap_size{app_kubernetes_io_name=\"nodeport-proxy-envoy\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\".*$cluster.*\"})  - sum(envoy_cluster_membership_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\",envoy_cluster_name=~\".*$cluster.*\"}))"
    }
   ]
  },
  {
   "title": "Cluster State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(envoy_cluster_membership_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\",envoy_cluster_name=~\".*$cluster.*\"})-sum(envoy_cluster_membership_healthy{app_kubernetes_io_name=\"nodeport-proxy-envoy\",envoy_cluster_name=~\".*$cluster.*\"})) == bool 0"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app_kubernetes_io_name=\"nodeport-proxy-envoy\",envoy_cluster_name=~\"cluster-$cluster.*\"}) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\",envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}})"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_rx_bytes_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}}) - in"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_cx_tx_bytes_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}} ({{service}}) - out"
    }
   ]
  },
  {
   "title": "Downstream members",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-.*\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Tunneling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_cluster_name=~\"cluster-$cluster.*\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} 50% "
    }
   ]
  },
  {
   "title": "Downstream Total active requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_http_conn_manager_prefix=\"ingress_http\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_cx_rx_bytes_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "{{service}} - in"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_cx_tx_bytes_total{app_kubernetes_io_name=\"nodeport-proxy-envoy\", envoy_http_conn_manager_prefix=\"ingress_http\"}[1m]))",
     "legendFormat": "{{service}} - out"
    }
   ]
  }
 ]
}