{
 "title": "User Clusters",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cloud Providers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (cloud_provider) (count by (name, cloud_provider) (kubermatic_cluster_info))",
     "legendFormat": "{{ cloud_provider }}"
    }
   ]
  },
  {
   "title": "Datacenters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (datacenter) (count by (name, datacenter) (kubermatic_cluster_info))",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  {
   "title": "Total User Clusters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (type) (count by (name, type) (kubermatic_cluster_info))",
     "legendFormat": "{{ type }} clusters"
    }
   ]
  },
  {
   "title": "Cloud Provider History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (cloud_provider) (count by (name, cloud_provider) (kubermatic_cluster_info))",
     "legendFormat": "{{ cloud_provider }}"
    }
   ]
  },
  {
   "title": "Datacenter History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (datacenter) (count by (name, datacenter) (kubermatic_cluster_info))",
     "legendFormat": "{{ datacenter }}"
    }
   ]
  },
  { "title": "Kubernetes Releases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Minor Releases",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (master_version) (count by (name, master_version) (label_replace(kubermatic_cluster_info{type=\"kubernetes\"}, \"master_version\", \"$1\", \"master_version\", \"([0-9]+\\\\.[0-9]+).*\")))",
     "legendFormat": "{{ master_version }}"
    }
   ]
  },
  {
   "title": "Releases",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count by (master_version) (count by (name, master_version) (kubermatic_cluster_info{type=\"kubernetes\"}))",
     "legendFormat": "{{ master_version }}"
    }
   ]
  },
  {
   "title": "Minor Release History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (master_version) (count by (name, master_version) (label_replace(kubermatic_cluster_info{type=\"kubernetes\"}, \"master_version\", \"$1\", \"master_version\", \"([0-9]+\\\\.[0-9]+).*\")))",
     "legendFormat": "{{ master_version }}"
    }
   ]
  },
  {
   "title": "Release History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count by (master_version) (count by (name, master_version) (kubermatic_cluster_info{type=\"kubernetes\"}))",
     "legendFormat": "{{ master_version }}"
    }
   ]
  }
 ]
}