// Code generated by go-swagger; DO NOT EDIT.

package openstack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListOpenstackNetworksNoCredentialsParams creates a new ListOpenstackNetworksNoCredentialsParams object
// with the default values initialized.
func NewListOpenstackNetworksNoCredentialsParams() *ListOpenstackNetworksNoCredentialsParams {
	var ()
	return &ListOpenstackNetworksNoCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListOpenstackNetworksNoCredentialsParamsWithTimeout creates a new ListOpenstackNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListOpenstackNetworksNoCredentialsParamsWithTimeout(timeout time.Duration) *ListOpenstackNetworksNoCredentialsParams {
	var ()
	return &ListOpenstackNetworksNoCredentialsParams{

		timeout: timeout,
	}
}

// NewListOpenstackNetworksNoCredentialsParamsWithContext creates a new ListOpenstackNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListOpenstackNetworksNoCredentialsParamsWithContext(ctx context.Context) *ListOpenstackNetworksNoCredentialsParams {
	var ()
	return &ListOpenstackNetworksNoCredentialsParams{

		Context: ctx,
	}
}

// NewListOpenstackNetworksNoCredentialsParamsWithHTTPClient creates a new ListOpenstackNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListOpenstackNetworksNoCredentialsParamsWithHTTPClient(client *http.Client) *ListOpenstackNetworksNoCredentialsParams {
	var ()
	return &ListOpenstackNetworksNoCredentialsParams{
		HTTPClient: client,
	}
}

/*ListOpenstackNetworksNoCredentialsParams contains all the parameters to send to the API endpoint
for the list openstack networks no credentials operation typically these are written to a http.Request
*/
type ListOpenstackNetworksNoCredentialsParams struct {

	/*ClusterID*/
	ClusterID string
	/*Dc*/
	DC string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithTimeout(timeout time.Duration) *ListOpenstackNetworksNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithContext(ctx context.Context) *ListOpenstackNetworksNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithHTTPClient(client *http.Client) *ListOpenstackNetworksNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithClusterID(clusterID string) *ListOpenstackNetworksNoCredentialsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDC adds the dc to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithDC(dc string) *ListOpenstackNetworksNoCredentialsParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetDC(dc string) {
	o.DC = dc
}

// WithProjectID adds the projectID to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) WithProjectID(projectID string) *ListOpenstackNetworksNoCredentialsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list openstack networks no credentials params
func (o *ListOpenstackNetworksNoCredentialsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListOpenstackNetworksNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
