{
 "title": "Fluent Bit",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,60m" }
  ]
 },
 "panels": [
  {
   "title": "Data Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(fluentbit_input_bytes_total{namespace=\"logging\"}[$interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Record Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(fluentbit_input_records_total{namespace=\"logging\"}[$interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Output Retry Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(fluentbit_output_retries_total{namespace=\"logging\"}[$interval]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Currently Open Files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (fluentbit_input_files_opened_total{namespace=\"logging\"} - fluentbit_input_files_closed_total{namespace=\"logging\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}