# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM docker.io/golang:1.25.5 AS builder

# import the GOPROXY variable via an arg and then use
# that arg to define the environment variable later on
ARG GOPROXY=
ARG GOCACHE=
ARG KUBERMATIC_EDITION=ce

ENV GOPROXY=$GOPROXY
ENV GOCACHE=$GOCACHE
ENV KUBERMATIC_EDITION=$KUBERMATIC_EDITION

WORKDIR /go/src/k8c.io/kubermatic
COPY . .
RUN make -C ./cmd/user-ssh-keys-agent build

FROM gcr.io/distroless/static-debian12
LABEL org.opencontainers.image.source="https://github.com/kubermatic/kubermatic/blob/main/cmd/user-ssh-keys-agent/Dockerfile.multiarch"
LABEL org.opencontainers.image.vendor="Kubermatic"
LABEL org.opencontainers.image.authors="support@kubermatic.com"

COPY --from=builder /go/src/k8c.io/kubermatic/cmd/user-ssh-keys-agent/_build/user-ssh-keys-agent /usr/local/bin/user-ssh-keys-agent
ENTRYPOINT ["/usr/local/bin/user-ssh-keys-agent"]
