{
 "title": "Go Processes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(go_threads, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(go_threads{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\",pod=\"$pod\"}, label_kubermatic_metrics_container)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "heap allocated"
    },
    {
     "expr": "avg(container_memory_rss{namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\"})",
     "legendFormat": "container rss"
    }
   ]
  },
  {
   "title": "Mallocs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(rate(go_memstats_mallocs_total{namespace=\"$namespace\",pod=\"$pod\"}[1m]))",
     "legendFormat": "malloc rate"
    }
   ]
  },
  {
   "title": "Go Versions",
   "type": "table",
   "gridPos": { "h": 18, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "count by (namespace, pod, version) (go_info{namespace!=\"\"})"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(go_gc_duration_seconds{namespace=\"$namespace\",pod=\"$pod\",quantile=\"0.5\"})",
     "legendFormat": "median"
    },
    {
     "expr": "avg(go_gc_duration_seconds{namespace=\"$namespace\",pod=\"$pod\",quantile=\"0.75\"}) ",
     "legendFormat": "75th quantile"
    },
    {
     "expr": "avg(go_memstats_gc_cpu_fraction{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "CPU fraction"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(go_goroutines{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "goroutines"
    },
    {
     "expr": "max(go_threads{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "threads"
    }
   ]
  }
 ]
}