// Code generated by go-swagger; DO NOT EDIT.

package vmwareclouddirector

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListVMwareCloudDirectorCatalogsNoCredentialsParams creates a new ListVMwareCloudDirectorCatalogsNoCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListVMwareCloudDirectorCatalogsNoCredentialsParams() *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	return &ListVMwareCloudDirectorCatalogsNoCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithTimeout creates a new ListVMwareCloudDirectorCatalogsNoCredentialsParams object
// with the ability to set a timeout on a request.
func NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithTimeout(timeout time.Duration) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	return &ListVMwareCloudDirectorCatalogsNoCredentialsParams{
		timeout: timeout,
	}
}

// NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithContext creates a new ListVMwareCloudDirectorCatalogsNoCredentialsParams object
// with the ability to set a context for a request.
func NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithContext(ctx context.Context) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	return &ListVMwareCloudDirectorCatalogsNoCredentialsParams{
		Context: ctx,
	}
}

// NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithHTTPClient creates a new ListVMwareCloudDirectorCatalogsNoCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListVMwareCloudDirectorCatalogsNoCredentialsParamsWithHTTPClient(client *http.Client) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	return &ListVMwareCloudDirectorCatalogsNoCredentialsParams{
		HTTPClient: client,
	}
}

/*
ListVMwareCloudDirectorCatalogsNoCredentialsParams contains all the parameters to send to the API endpoint

	for the list v mware cloud director catalogs no credentials operation.

	Typically these are written to a http.Request.
*/
type ListVMwareCloudDirectorCatalogsNoCredentialsParams struct {

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list v mware cloud director catalogs no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithDefaults() *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list v mware cloud director catalogs no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithTimeout(timeout time.Duration) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithContext(ctx context.Context) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithHTTPClient(client *http.Client) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithClusterID(clusterID string) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WithProjectID(projectID string) *ListVMwareCloudDirectorCatalogsNoCredentialsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list v mware cloud director catalogs no credentials params
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListVMwareCloudDirectorCatalogsNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
