// Code generated by go-swagger; DO NOT EDIT.

package kubevirt

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKubevirtVmiPresetParams creates a new GetKubevirtVmiPresetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetKubevirtVmiPresetParams() *GetKubevirtVmiPresetParams {
	return &GetKubevirtVmiPresetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetKubevirtVmiPresetParamsWithTimeout creates a new GetKubevirtVmiPresetParams object
// with the ability to set a timeout on a request.
func NewGetKubevirtVmiPresetParamsWithTimeout(timeout time.Duration) *GetKubevirtVmiPresetParams {
	return &GetKubevirtVmiPresetParams{
		timeout: timeout,
	}
}

// NewGetKubevirtVmiPresetParamsWithContext creates a new GetKubevirtVmiPresetParams object
// with the ability to set a context for a request.
func NewGetKubevirtVmiPresetParamsWithContext(ctx context.Context) *GetKubevirtVmiPresetParams {
	return &GetKubevirtVmiPresetParams{
		Context: ctx,
	}
}

// NewGetKubevirtVmiPresetParamsWithHTTPClient creates a new GetKubevirtVmiPresetParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetKubevirtVmiPresetParamsWithHTTPClient(client *http.Client) *GetKubevirtVmiPresetParams {
	return &GetKubevirtVmiPresetParams{
		HTTPClient: client,
	}
}

/* GetKubevirtVmiPresetParams contains all the parameters to send to the API endpoint
   for the get kubevirt vmi preset operation.

   Typically these are written to a http.Request.
*/
type GetKubevirtVmiPresetParams struct {

	// Credential.
	Credential *string

	// KvKubeconfig.
	KvKubeconfig *string

	// PresetID.
	PresetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get kubevirt vmi preset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKubevirtVmiPresetParams) WithDefaults() *GetKubevirtVmiPresetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get kubevirt vmi preset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetKubevirtVmiPresetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithTimeout(timeout time.Duration) *GetKubevirtVmiPresetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithContext(ctx context.Context) *GetKubevirtVmiPresetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithHTTPClient(client *http.Client) *GetKubevirtVmiPresetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCredential adds the credential to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithCredential(credential *string) *GetKubevirtVmiPresetParams {
	o.SetCredential(credential)
	return o
}

// SetCredential adds the credential to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetCredential(credential *string) {
	o.Credential = credential
}

// WithKvKubeconfig adds the kvKubeconfig to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithKvKubeconfig(kvKubeconfig *string) *GetKubevirtVmiPresetParams {
	o.SetKvKubeconfig(kvKubeconfig)
	return o
}

// SetKvKubeconfig adds the kvKubeconfig to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetKvKubeconfig(kvKubeconfig *string) {
	o.KvKubeconfig = kvKubeconfig
}

// WithPresetName adds the presetID to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) WithPresetName(presetID string) *GetKubevirtVmiPresetParams {
	o.SetPresetName(presetID)
	return o
}

// SetPresetName adds the presetId to the get kubevirt vmi preset params
func (o *GetKubevirtVmiPresetParams) SetPresetName(presetID string) {
	o.PresetName = presetID
}

// WriteToRequest writes these params to a swagger request
func (o *GetKubevirtVmiPresetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Credential != nil {

		// header param Credential
		if err := r.SetHeaderParam("Credential", *o.Credential); err != nil {
			return err
		}
	}

	if o.KvKubeconfig != nil {

		// header param KvKubeconfig
		if err := r.SetHeaderParam("KvKubeconfig", *o.KvKubeconfig); err != nil {
			return err
		}
	}

	// path param preset_id
	if err := r.SetPathParam("preset_id", o.PresetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
