// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAlertmanagerParams creates a new DeleteAlertmanagerParams object
// with the default values initialized.
func NewDeleteAlertmanagerParams() *DeleteAlertmanagerParams {
	var ()
	return &DeleteAlertmanagerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAlertmanagerParamsWithTimeout creates a new DeleteAlertmanagerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAlertmanagerParamsWithTimeout(timeout time.Duration) *DeleteAlertmanagerParams {
	var ()
	return &DeleteAlertmanagerParams{

		timeout: timeout,
	}
}

// NewDeleteAlertmanagerParamsWithContext creates a new DeleteAlertmanagerParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAlertmanagerParamsWithContext(ctx context.Context) *DeleteAlertmanagerParams {
	var ()
	return &DeleteAlertmanagerParams{

		Context: ctx,
	}
}

// NewDeleteAlertmanagerParamsWithHTTPClient creates a new DeleteAlertmanagerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAlertmanagerParamsWithHTTPClient(client *http.Client) *DeleteAlertmanagerParams {
	var ()
	return &DeleteAlertmanagerParams{
		HTTPClient: client,
	}
}

/*DeleteAlertmanagerParams contains all the parameters to send to the API endpoint
for the delete alertmanager operation typically these are written to a http.Request
*/
type DeleteAlertmanagerParams struct {

	/*ClusterID*/
	ClusterID string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete alertmanager params
func (o *DeleteAlertmanagerParams) WithTimeout(timeout time.Duration) *DeleteAlertmanagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete alertmanager params
func (o *DeleteAlertmanagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete alertmanager params
func (o *DeleteAlertmanagerParams) WithContext(ctx context.Context) *DeleteAlertmanagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete alertmanager params
func (o *DeleteAlertmanagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete alertmanager params
func (o *DeleteAlertmanagerParams) WithHTTPClient(client *http.Client) *DeleteAlertmanagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete alertmanager params
func (o *DeleteAlertmanagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the delete alertmanager params
func (o *DeleteAlertmanagerParams) WithClusterID(clusterID string) *DeleteAlertmanagerParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete alertmanager params
func (o *DeleteAlertmanagerParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the delete alertmanager params
func (o *DeleteAlertmanagerParams) WithProjectID(projectID string) *DeleteAlertmanagerParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete alertmanager params
func (o *DeleteAlertmanagerParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAlertmanagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
