// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/kubermatic/v2/pkg/test/e2e/utils/apiclient/models"
)

// GetOidcClusterKubeloginCmdReader is a Reader for the GetOidcClusterKubeloginCmd structure.
type GetOidcClusterKubeloginCmdReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOidcClusterKubeloginCmdReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOidcClusterKubeloginCmdOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetOidcClusterKubeloginCmdUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetOidcClusterKubeloginCmdForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetOidcClusterKubeloginCmdDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetOidcClusterKubeloginCmdOK creates a GetOidcClusterKubeloginCmdOK with default headers values
func NewGetOidcClusterKubeloginCmdOK() *GetOidcClusterKubeloginCmdOK {
	return &GetOidcClusterKubeloginCmdOK{}
}

/*GetOidcClusterKubeloginCmdOK handles this case with default header values.

KubeloginCommand
*/
type GetOidcClusterKubeloginCmdOK struct {
	Payload models.KubeloginCommand
}

func (o *GetOidcClusterKubeloginCmdOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/kubelogincmd][%d] getOidcClusterKubeloginCmdOK  %+v", 200, o.Payload)
}

func (o *GetOidcClusterKubeloginCmdOK) GetPayload() models.KubeloginCommand {
	return o.Payload
}

func (o *GetOidcClusterKubeloginCmdOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOidcClusterKubeloginCmdUnauthorized creates a GetOidcClusterKubeloginCmdUnauthorized with default headers values
func NewGetOidcClusterKubeloginCmdUnauthorized() *GetOidcClusterKubeloginCmdUnauthorized {
	return &GetOidcClusterKubeloginCmdUnauthorized{}
}

/*GetOidcClusterKubeloginCmdUnauthorized handles this case with default header values.

EmptyResponse is a empty response
*/
type GetOidcClusterKubeloginCmdUnauthorized struct {
}

func (o *GetOidcClusterKubeloginCmdUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/kubelogincmd][%d] getOidcClusterKubeloginCmdUnauthorized ", 401)
}

func (o *GetOidcClusterKubeloginCmdUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOidcClusterKubeloginCmdForbidden creates a GetOidcClusterKubeloginCmdForbidden with default headers values
func NewGetOidcClusterKubeloginCmdForbidden() *GetOidcClusterKubeloginCmdForbidden {
	return &GetOidcClusterKubeloginCmdForbidden{}
}

/*GetOidcClusterKubeloginCmdForbidden handles this case with default header values.

EmptyResponse is a empty response
*/
type GetOidcClusterKubeloginCmdForbidden struct {
}

func (o *GetOidcClusterKubeloginCmdForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/kubelogincmd][%d] getOidcClusterKubeloginCmdForbidden ", 403)
}

func (o *GetOidcClusterKubeloginCmdForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOidcClusterKubeloginCmdDefault creates a GetOidcClusterKubeloginCmdDefault with default headers values
func NewGetOidcClusterKubeloginCmdDefault(code int) *GetOidcClusterKubeloginCmdDefault {
	return &GetOidcClusterKubeloginCmdDefault{
		_statusCode: code,
	}
}

/*GetOidcClusterKubeloginCmdDefault handles this case with default header values.

errorResponse
*/
type GetOidcClusterKubeloginCmdDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get oidc cluster kubelogin cmd default response
func (o *GetOidcClusterKubeloginCmdDefault) Code() int {
	return o._statusCode
}

func (o *GetOidcClusterKubeloginCmdDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/clusters/{cluster_id}/kubelogincmd][%d] getOidcClusterKubeloginCmd default  %+v", o._statusCode, o.Payload)
}

func (o *GetOidcClusterKubeloginCmdDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetOidcClusterKubeloginCmdDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
