// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListClusterServiceAccountParams creates a new ListClusterServiceAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListClusterServiceAccountParams() *ListClusterServiceAccountParams {
	return &ListClusterServiceAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListClusterServiceAccountParamsWithTimeout creates a new ListClusterServiceAccountParams object
// with the ability to set a timeout on a request.
func NewListClusterServiceAccountParamsWithTimeout(timeout time.Duration) *ListClusterServiceAccountParams {
	return &ListClusterServiceAccountParams{
		timeout: timeout,
	}
}

// NewListClusterServiceAccountParamsWithContext creates a new ListClusterServiceAccountParams object
// with the ability to set a context for a request.
func NewListClusterServiceAccountParamsWithContext(ctx context.Context) *ListClusterServiceAccountParams {
	return &ListClusterServiceAccountParams{
		Context: ctx,
	}
}

// NewListClusterServiceAccountParamsWithHTTPClient creates a new ListClusterServiceAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewListClusterServiceAccountParamsWithHTTPClient(client *http.Client) *ListClusterServiceAccountParams {
	return &ListClusterServiceAccountParams{
		HTTPClient: client,
	}
}

/*
ListClusterServiceAccountParams contains all the parameters to send to the API endpoint

	for the list cluster service account operation.

	Typically these are written to a http.Request.
*/
type ListClusterServiceAccountParams struct {

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list cluster service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListClusterServiceAccountParams) WithDefaults() *ListClusterServiceAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list cluster service account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListClusterServiceAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list cluster service account params
func (o *ListClusterServiceAccountParams) WithTimeout(timeout time.Duration) *ListClusterServiceAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list cluster service account params
func (o *ListClusterServiceAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list cluster service account params
func (o *ListClusterServiceAccountParams) WithContext(ctx context.Context) *ListClusterServiceAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list cluster service account params
func (o *ListClusterServiceAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list cluster service account params
func (o *ListClusterServiceAccountParams) WithHTTPClient(client *http.Client) *ListClusterServiceAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list cluster service account params
func (o *ListClusterServiceAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list cluster service account params
func (o *ListClusterServiceAccountParams) WithClusterID(clusterID string) *ListClusterServiceAccountParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list cluster service account params
func (o *ListClusterServiceAccountParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list cluster service account params
func (o *ListClusterServiceAccountParams) WithProjectID(projectID string) *ListClusterServiceAccountParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list cluster service account params
func (o *ListClusterServiceAccountParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListClusterServiceAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
