// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewResetAlertmanagerParams creates a new ResetAlertmanagerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewResetAlertmanagerParams() *ResetAlertmanagerParams {
	return &ResetAlertmanagerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewResetAlertmanagerParamsWithTimeout creates a new ResetAlertmanagerParams object
// with the ability to set a timeout on a request.
func NewResetAlertmanagerParamsWithTimeout(timeout time.Duration) *ResetAlertmanagerParams {
	return &ResetAlertmanagerParams{
		timeout: timeout,
	}
}

// NewResetAlertmanagerParamsWithContext creates a new ResetAlertmanagerParams object
// with the ability to set a context for a request.
func NewResetAlertmanagerParamsWithContext(ctx context.Context) *ResetAlertmanagerParams {
	return &ResetAlertmanagerParams{
		Context: ctx,
	}
}

// NewResetAlertmanagerParamsWithHTTPClient creates a new ResetAlertmanagerParams object
// with the ability to set a custom HTTPClient for a request.
func NewResetAlertmanagerParamsWithHTTPClient(client *http.Client) *ResetAlertmanagerParams {
	return &ResetAlertmanagerParams{
		HTTPClient: client,
	}
}

/* ResetAlertmanagerParams contains all the parameters to send to the API endpoint
   for the reset alertmanager operation.

   Typically these are written to a http.Request.
*/
type ResetAlertmanagerParams struct {

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the reset alertmanager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResetAlertmanagerParams) WithDefaults() *ResetAlertmanagerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the reset alertmanager params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ResetAlertmanagerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the reset alertmanager params
func (o *ResetAlertmanagerParams) WithTimeout(timeout time.Duration) *ResetAlertmanagerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reset alertmanager params
func (o *ResetAlertmanagerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reset alertmanager params
func (o *ResetAlertmanagerParams) WithContext(ctx context.Context) *ResetAlertmanagerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reset alertmanager params
func (o *ResetAlertmanagerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reset alertmanager params
func (o *ResetAlertmanagerParams) WithHTTPClient(client *http.Client) *ResetAlertmanagerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reset alertmanager params
func (o *ResetAlertmanagerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the reset alertmanager params
func (o *ResetAlertmanagerParams) WithClusterID(clusterID string) *ResetAlertmanagerParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the reset alertmanager params
func (o *ResetAlertmanagerParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the reset alertmanager params
func (o *ResetAlertmanagerParams) WithProjectID(projectID string) *ResetAlertmanagerParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the reset alertmanager params
func (o *ResetAlertmanagerParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ResetAlertmanagerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
