{
 "title": "Query",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "monitoring" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_name=~\"prometheus-thanos-query.*\"}, pod)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Instant Query API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\",code!~\"2..\"}[$interval])) / sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval])) * 1 / sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Range Query API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\",code!~\"2..\"}[$interval])) / sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval])) * 1 / sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Query Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of requests against /query for the given time, with handlers and codes.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (handler, status_code)",
       "legendFormat": "{{handler}} {{status_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of handled requests, in more detail.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",code!~\"2..\"}[$interval])) by (handler, code)",
       "legendFormat": "{{handler}} {{code}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (handler, le)) * 1",
       "legendFormat": "P99 {{handler}}"
      },
      {
       "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (handler) * 1 / sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (handler)",
       "legendFormat": "mean {{handler}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (handler, le)) * 1",
       "legendFormat": "P50 {{handler}}"
      }
     ]
    }
   ]
  },
  { "title": "gRPC (Unary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_client_started_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(grpc_client_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_client_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))\n",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Unary gRPC requests, with grpc methods and codes from other queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of handled requests from other queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)\n",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from other queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P99 {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_client_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_client_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))\n",
       "legendFormat": "mean {{grpc_method}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "gRPC (Stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests from other queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) / sum(rate(grpc_client_started_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from other queriers, in quantiles",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(grpc_client_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_client_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))\n",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Streamed gRPC requests, with grpc methods and codes.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the the total number of handled requests.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)\n",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P99 {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_client_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_client_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))\n",
       "legendFormat": "mean {{grpc_method}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of DNS lookups to discover stores.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_querier_store_apis_dns_lookups_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "lookups"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of failures compared to the the total number of executed DNS lookups.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_querier_store_apis_dns_failures_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_querier_store_apis_dns_lookups_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "alloc all {{pod}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "alloc heap {{pod}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate all {{pod}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "alloc rate heap {{pod}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "inuse stack {{pod}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "inuse heap {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Time Quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  }
 ]
}