{
 "title": "Sidecar",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "monitoring" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=~\"prometheus-[0-9]+\",container=\"thanos\"}, pod)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "gRPC (Unary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99 "
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval]))\n",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Unary gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=~\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{ grpc_method }} {{ grpc_code }}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)\n",
       "legendFormat": "{{ grpc_method }} {{ grpc_code }}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P99 {{ grpc_method }}"
      },
      {
       "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval]))\n",
       "legendFormat": "mean {{ grpc_method }}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{ grpc_method }}"
      }
     ]
    }
   ]
  },
  { "title": "gRPC (Stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval]))\n",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Streamed gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)\n",
       "legendFormat": "{{ grpc_method }} {{ grpc_code }}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (job, grpc_method, le)) * 1",
       "legendFormat": "P99 {{ grpc_method }}"
      },
      {
       "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval]))",
       "legendFormat": "mean {{ grpc_method }}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{ grpc_method }}"
      }
     ]
    }
   ]
  },
  { "title": "Last Updated", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Successful Upload",
   "type": "table",
   "description": "Shows the relative time of last successful upload to the object-store bucket.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "time() - max(thanos_objstore_bucket_last_successful_upload_time{namespace=\"$namespace\",job=\"thanos-sidecar\"}) by (bucket)"
    }
   ]
  },
  { "title": "Bucket Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) by (operation)",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) / sum(rate(thanos_objstore_bucket_operations_total{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_duration_seconds_sum{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) * 1 / sum(rate(thanos_objstore_bucket_operation_duration_seconds_count{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "alloc all {{pod}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "alloc heap {{pod}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}[$interval])",
       "legendFormat": "alloc rate all {{pod}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}[$interval])",
       "legendFormat": "alloc rate heap {{pod}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "inuse stack {{pod}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "inuse heap {{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\",job=\"thanos-sidecar\",pod=~\"$pod\"}",
       "legendFormat": "{{quantile}} {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}