{
 "title": "Store",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "monitoring" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",created_by_name=~\"prometheus-thanos-store.*\"}, pod)"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "gRPC (Unary)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Unary gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P99 {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval]))",
       "legendFormat": "mean {{grpc_method}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"unary\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "gRPC (Stream)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_server_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))\n",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate",
     "type": "graph",
     "description": "Shows rate of handled Streamed gRPC requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, grpc_code)",
       "legendFormat": "{{grpc_method}} {{grpc_code}}"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P99 {{grpc_method}}"
      },
      {
       "expr": "sum(rate(grpc_client_handling_seconds_sum{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) * 1\n/\nsum(rate(grpc_client_handling_seconds_count{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval]))\n",
       "legendFormat": "mean {{grpc_method}}"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(grpc_client_handling_seconds_bucket{namespace=\"$namespace\",job=\"pods\",grpc_type=\"server_stream\"}[$interval])) by (grpc_method, le)) * 1",
       "legendFormat": "P50 {{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "Bucket Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "Shows rate of execution for operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operations_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed operations against the bucket.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_failures_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_objstore_bucket_operations_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to execute operations against the bucket, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_duration_seconds_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) * 1 / sum(rate(thanos_objstore_bucket_operation_duration_seconds_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Block Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Block Load Rate",
   "type": "graph",
   "description": "Shows rate of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_loads_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "block loads"
    }
   ]
  },
  {
   "title": "Block Load Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of block loads from the bucket.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_load_failures_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_block_loads_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Block Drop Rate",
   "type": "graph",
   "description": "Shows rate of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_drops_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (operation)",
     "legendFormat": "block drops"
    }
   ]
  },
  {
   "title": "Block Drop Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of block drops.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_bucket_store_block_drop_failures_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_block_drops_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "Cache Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Requests",
   "type": "graph",
   "description": "Show rate of cache requests.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_requests_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (item_type)",
     "legendFormat": "{{item_type}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of cache hits.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_hits_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (item_type)",
     "legendFormat": "{{item_type}}"
    }
   ]
  },
  {
   "title": "Added",
   "type": "graph",
   "description": "Show rate of added items to cache.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_added_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (item_type)",
     "legendFormat": "{{item_type}}"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "graph",
   "description": "Show rate of evicted items from cache.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_store_index_cache_items_evicted_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (item_type)",
     "legendFormat": "{{item_type}}"
    }
   ]
  },
  { "title": "Store Sent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Chunk Size",
   "type": "graph",
   "description": "Shows size of chunks that have sent to the bucket, in bytes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_sent_chunk_size_bytes_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_sent_chunk_size_bytes_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_sent_chunk_size_bytes_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Series Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Block queried",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_blocks_queried{namespace=\"$namespace\",job=\"pods\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_blocks_queried_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_series_blocks_queried_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "thanos_bucket_store_series_blocks_queried{namespace=\"$namespace\",job=\"pods\",quantile=\"0.50\"}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Data Fetched",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_data_fetched{namespace=\"$namespace\",job=\"pods\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_data_fetched_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_series_data_fetched_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "thanos_bucket_store_series_data_fetched{namespace=\"$namespace\",job=\"pods\",quantile=\"0.50\"}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Result series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_result_series{namespace=\"$namespace\",job=\"pods\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_result_series_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_series_result_series_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "thanos_bucket_store_series_result_series{namespace=\"$namespace\",job=\"pods\",quantile=\"0.50\"}",
     "legendFormat": "P50"
    }
   ]
  },
  { "title": "Series Operation Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Get All",
   "type": "graph",
   "description": "Shows how long has it taken to get all series.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_get_all_duration_seconds_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) * 1 / sum(rate(thanos_bucket_store_series_get_all_duration_seconds_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "description": "Shows how long has it taken to merge series.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) * 1 / sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_merge_duration_seconds_bucket_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Result series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "thanos_bucket_store_series_result_series{namespace=\"$namespace\",job=\"pods\",quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_result_series_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_bucket_store_series_result_series_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "thanos_bucket_store_series_result_series{namespace=\"$namespace\",job=\"pods\",quantile=\"0.50\"}",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Gate",
   "type": "graph",
   "description": "Shows how long has it taken for a series to wait at the gate.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket_sum{namespace=\"$namespace\",job=\"pods\"}[$interval])) * 1 / sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket_count{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "mean"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_bucket_store_series_gate_duration_seconds_bucket_bucket{namespace=\"$namespace\",job=\"pods\"}[$interval])) by (le)) * 1",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "alloc all {{pod}}"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "alloc heap {{pod}}"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}[$interval])",
       "legendFormat": "alloc rate all {{pod}}"
      },
      {
       "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}[$interval])",
       "legendFormat": "alloc rate heap {{pod}}"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "inuse stack {{pod}}"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "inuse heap {{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "GC Time Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{namespace=\"$namespace\",job=\"pods\",pod=~\"$pod\"}",
       "legendFormat": "{{quantile}} {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}