{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "disk_storage_used{app=\"minio\"} / disk_storage_total{app=\"minio\"} * 100"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_storage_available{app=\"minio\"}",
     "legendFormat": "available"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(s3_tx_bytes_total{app=\"minio\"}[$interval])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(s3_rx_bytes_total{app=\"minio\"}[$interval])",
     "legendFormat": "received"
    }
   ]
  }
 ]
}