{
 "title": "Go Processes (Deployments)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(go_threads, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"} , deployment)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=~\"$deployment-.*\"} , pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} - heap allocated"
    },
    {
     "expr": "sum by (pod_name) (container_memory_rss{namespace=\"$namespace\",pod_name=~\"$pod\"})",
     "legendFormat": "{{ pod_name }} - container rss"
    }
   ]
  },
  {
   "title": "Mallocs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memstats_mallocs_total{namespace=\"$namespace\",pod=~\"$pod\"}[1m]))",
     "legendFormat": "malloc rate"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (go_gc_duration_seconds{namespace=\"$namespace\",pod=~\"$pod\",quantile=\"0.5\"})",
     "legendFormat": "{{ pod }} - median"
    },
    {
     "expr": "avg by (pod) (go_gc_duration_seconds{namespace=\"$namespace\",pod=~\"$pod\",quantile=\"0.75\"}) ",
     "legendFormat": "{{ pod }} - 75th quantile"
    },
    {
     "expr": "avg by (pod) (go_memstats_gc_cpu_fraction{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} - CPU fraction"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (go_goroutines{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} - goroutines"
    },
    {
     "expr": "max by (pod) (go_threads{namespace=\"$namespace\",pod=~\"$pod\"})",
     "legendFormat": "{{ pod }} - threads"
    }
   ]
  }
 ]
}