// Code generated by client-gen. DO NOT EDIT.

package v1

type AddonExpansion interface{}

type ClusterExpansion interface{}

type ProjectExpansion interface{}

type UserExpansion interface{}

type UserSSHKeyExpansion interface{}
