{
 "title": "Machine Controller",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "User Cluster",
    "query": "label_values(job:machine_controller_machines:sum,cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Machines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:machine_controller_machines:sum{cluster=~\"$cluster\"}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:machine_controller_workers:sum{cluster=~\"$cluster\"}",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "5min Error Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:machine_controller_errors_total:rate5m{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  }
 ]
}