// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListAWSZonesNoCredentialsParams creates a new ListAWSZonesNoCredentialsParams object
// with the default values initialized.
func NewListAWSZonesNoCredentialsParams() *ListAWSZonesNoCredentialsParams {
	var ()
	return &ListAWSZonesNoCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAWSZonesNoCredentialsParamsWithTimeout creates a new ListAWSZonesNoCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAWSZonesNoCredentialsParamsWithTimeout(timeout time.Duration) *ListAWSZonesNoCredentialsParams {
	var ()
	return &ListAWSZonesNoCredentialsParams{

		timeout: timeout,
	}
}

// NewListAWSZonesNoCredentialsParamsWithContext creates a new ListAWSZonesNoCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAWSZonesNoCredentialsParamsWithContext(ctx context.Context) *ListAWSZonesNoCredentialsParams {
	var ()
	return &ListAWSZonesNoCredentialsParams{

		Context: ctx,
	}
}

// NewListAWSZonesNoCredentialsParamsWithHTTPClient creates a new ListAWSZonesNoCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAWSZonesNoCredentialsParamsWithHTTPClient(client *http.Client) *ListAWSZonesNoCredentialsParams {
	var ()
	return &ListAWSZonesNoCredentialsParams{
		HTTPClient: client,
	}
}

/*ListAWSZonesNoCredentialsParams contains all the parameters to send to the API endpoint
for the list a w s zones no credentials operation typically these are written to a http.Request
*/
type ListAWSZonesNoCredentialsParams struct {

	/*ClusterID*/
	ClusterID string
	/*Dc*/
	Dc string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithTimeout(timeout time.Duration) *ListAWSZonesNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithContext(ctx context.Context) *ListAWSZonesNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithHTTPClient(client *http.Client) *ListAWSZonesNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithClusterID(clusterID string) *ListAWSZonesNoCredentialsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDc adds the dc to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithDc(dc string) *ListAWSZonesNoCredentialsParams {
	o.SetDc(dc)
	return o
}

// SetDc adds the dc to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetDc(dc string) {
	o.Dc = dc
}

// WithProjectID adds the projectID to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) WithProjectID(projectID string) *ListAWSZonesNoCredentialsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list a w s zones no credentials params
func (o *ListAWSZonesNoCredentialsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListAWSZonesNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.Dc); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
