// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAdmissionPluginParams creates a new GetAdmissionPluginParams object
// with the default values initialized.
func NewGetAdmissionPluginParams() *GetAdmissionPluginParams {
	var ()
	return &GetAdmissionPluginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAdmissionPluginParamsWithTimeout creates a new GetAdmissionPluginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAdmissionPluginParamsWithTimeout(timeout time.Duration) *GetAdmissionPluginParams {
	var ()
	return &GetAdmissionPluginParams{

		timeout: timeout,
	}
}

// NewGetAdmissionPluginParamsWithContext creates a new GetAdmissionPluginParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAdmissionPluginParamsWithContext(ctx context.Context) *GetAdmissionPluginParams {
	var ()
	return &GetAdmissionPluginParams{

		Context: ctx,
	}
}

// NewGetAdmissionPluginParamsWithHTTPClient creates a new GetAdmissionPluginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAdmissionPluginParamsWithHTTPClient(client *http.Client) *GetAdmissionPluginParams {
	var ()
	return &GetAdmissionPluginParams{
		HTTPClient: client,
	}
}

/*GetAdmissionPluginParams contains all the parameters to send to the API endpoint
for the get admission plugin operation typically these are written to a http.Request
*/
type GetAdmissionPluginParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get admission plugin params
func (o *GetAdmissionPluginParams) WithTimeout(timeout time.Duration) *GetAdmissionPluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get admission plugin params
func (o *GetAdmissionPluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get admission plugin params
func (o *GetAdmissionPluginParams) WithContext(ctx context.Context) *GetAdmissionPluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get admission plugin params
func (o *GetAdmissionPluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get admission plugin params
func (o *GetAdmissionPluginParams) WithHTTPClient(client *http.Client) *GetAdmissionPluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get admission plugin params
func (o *GetAdmissionPluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get admission plugin params
func (o *GetAdmissionPluginParams) WithName(name string) *GetAdmissionPluginParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get admission plugin params
func (o *GetAdmissionPluginParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAdmissionPluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
