// Code generated by go-swagger; DO NOT EDIT.

package operatingsystemprofile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/kubermatic/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListOperatingSystemProfilesReader is a Reader for the ListOperatingSystemProfiles structure.
type ListOperatingSystemProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOperatingSystemProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOperatingSystemProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListOperatingSystemProfilesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListOperatingSystemProfilesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListOperatingSystemProfilesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOperatingSystemProfilesOK creates a ListOperatingSystemProfilesOK with default headers values
func NewListOperatingSystemProfilesOK() *ListOperatingSystemProfilesOK {
	return &ListOperatingSystemProfilesOK{}
}

/* ListOperatingSystemProfilesOK describes a response with status code 200, with default header values.

OperatingSystemProfile
*/
type ListOperatingSystemProfilesOK struct {
	Payload []*models.OperatingSystemProfile
}

func (o *ListOperatingSystemProfilesOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/operatingsystemprofiles][%d] listOperatingSystemProfilesOK  %+v", 200, o.Payload)
}
func (o *ListOperatingSystemProfilesOK) GetPayload() []*models.OperatingSystemProfile {
	return o.Payload
}

func (o *ListOperatingSystemProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOperatingSystemProfilesUnauthorized creates a ListOperatingSystemProfilesUnauthorized with default headers values
func NewListOperatingSystemProfilesUnauthorized() *ListOperatingSystemProfilesUnauthorized {
	return &ListOperatingSystemProfilesUnauthorized{}
}

/* ListOperatingSystemProfilesUnauthorized describes a response with status code 401, with default header values.

EmptyResponse is a empty response
*/
type ListOperatingSystemProfilesUnauthorized struct {
}

func (o *ListOperatingSystemProfilesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/operatingsystemprofiles][%d] listOperatingSystemProfilesUnauthorized ", 401)
}

func (o *ListOperatingSystemProfilesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListOperatingSystemProfilesForbidden creates a ListOperatingSystemProfilesForbidden with default headers values
func NewListOperatingSystemProfilesForbidden() *ListOperatingSystemProfilesForbidden {
	return &ListOperatingSystemProfilesForbidden{}
}

/* ListOperatingSystemProfilesForbidden describes a response with status code 403, with default header values.

EmptyResponse is a empty response
*/
type ListOperatingSystemProfilesForbidden struct {
}

func (o *ListOperatingSystemProfilesForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/operatingsystemprofiles][%d] listOperatingSystemProfilesForbidden ", 403)
}

func (o *ListOperatingSystemProfilesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListOperatingSystemProfilesDefault creates a ListOperatingSystemProfilesDefault with default headers values
func NewListOperatingSystemProfilesDefault(code int) *ListOperatingSystemProfilesDefault {
	return &ListOperatingSystemProfilesDefault{
		_statusCode: code,
	}
}

/* ListOperatingSystemProfilesDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListOperatingSystemProfilesDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list operating system profiles default response
func (o *ListOperatingSystemProfilesDefault) Code() int {
	return o._statusCode
}

func (o *ListOperatingSystemProfilesDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/seeds/{seed_name}/operatingsystemprofiles][%d] listOperatingSystemProfiles default  %+v", o._statusCode, o.Payload)
}
func (o *ListOperatingSystemProfilesDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListOperatingSystemProfilesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
