FROM alpine:3.7

LABEL maintainer "henrik@loodse.com"

ADD ./canal /addons/canal
ADD ./dashboard /addons/dashboard
ADD ./dns /addons/dns
ADD ./heapster /addons/heapster
ADD ./kube-proxy /addons/kube-proxy
ADD ./openvpn /addons/openvpn
ADD ./rbac /addons/rbac
