{
 "title": "Prometheus Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(prom_exporter_pod_cpu_usage, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_pod_cpu_usage{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_pod_memory_usage{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "WAL Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_wal_size{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "WAL Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_wal_files{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Current Checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (prom_exporter_wal_checkpoint{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Checkpoint Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_wal_checkpoint_size{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_blocks{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_data_size{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Temporary Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_temp_blocks{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Temporary Block Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (pod) (prom_exporter_temp_blocks_size{pod=~\"$pod\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}