// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteRoleBindingParams creates a new DeleteRoleBindingParams object
// with the default values initialized.
func NewDeleteRoleBindingParams() *DeleteRoleBindingParams {
	var ()
	return &DeleteRoleBindingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRoleBindingParamsWithTimeout creates a new DeleteRoleBindingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteRoleBindingParamsWithTimeout(timeout time.Duration) *DeleteRoleBindingParams {
	var ()
	return &DeleteRoleBindingParams{

		timeout: timeout,
	}
}

// NewDeleteRoleBindingParamsWithContext creates a new DeleteRoleBindingParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteRoleBindingParamsWithContext(ctx context.Context) *DeleteRoleBindingParams {
	var ()
	return &DeleteRoleBindingParams{

		Context: ctx,
	}
}

// NewDeleteRoleBindingParamsWithHTTPClient creates a new DeleteRoleBindingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteRoleBindingParamsWithHTTPClient(client *http.Client) *DeleteRoleBindingParams {
	var ()
	return &DeleteRoleBindingParams{
		HTTPClient: client,
	}
}

/*DeleteRoleBindingParams contains all the parameters to send to the API endpoint
for the delete role binding operation typically these are written to a http.Request
*/
type DeleteRoleBindingParams struct {

	/*BindingID*/
	BindingID string
	/*ClusterID*/
	ClusterID string
	/*Dc*/
	Dc string
	/*Namespace*/
	Namespace string
	/*ProjectID*/
	ProjectID string
	/*RoleID*/
	RoleID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete role binding params
func (o *DeleteRoleBindingParams) WithTimeout(timeout time.Duration) *DeleteRoleBindingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete role binding params
func (o *DeleteRoleBindingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete role binding params
func (o *DeleteRoleBindingParams) WithContext(ctx context.Context) *DeleteRoleBindingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete role binding params
func (o *DeleteRoleBindingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete role binding params
func (o *DeleteRoleBindingParams) WithHTTPClient(client *http.Client) *DeleteRoleBindingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete role binding params
func (o *DeleteRoleBindingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBindingID adds the bindingID to the delete role binding params
func (o *DeleteRoleBindingParams) WithBindingID(bindingID string) *DeleteRoleBindingParams {
	o.SetBindingID(bindingID)
	return o
}

// SetBindingID adds the bindingId to the delete role binding params
func (o *DeleteRoleBindingParams) SetBindingID(bindingID string) {
	o.BindingID = bindingID
}

// WithClusterID adds the clusterID to the delete role binding params
func (o *DeleteRoleBindingParams) WithClusterID(clusterID string) *DeleteRoleBindingParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete role binding params
func (o *DeleteRoleBindingParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDc adds the dc to the delete role binding params
func (o *DeleteRoleBindingParams) WithDc(dc string) *DeleteRoleBindingParams {
	o.SetDc(dc)
	return o
}

// SetDc adds the dc to the delete role binding params
func (o *DeleteRoleBindingParams) SetDc(dc string) {
	o.Dc = dc
}

// WithNamespace adds the namespace to the delete role binding params
func (o *DeleteRoleBindingParams) WithNamespace(namespace string) *DeleteRoleBindingParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete role binding params
func (o *DeleteRoleBindingParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithProjectID adds the projectID to the delete role binding params
func (o *DeleteRoleBindingParams) WithProjectID(projectID string) *DeleteRoleBindingParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the delete role binding params
func (o *DeleteRoleBindingParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WithRoleID adds the roleID to the delete role binding params
func (o *DeleteRoleBindingParams) WithRoleID(roleID string) *DeleteRoleBindingParams {
	o.SetRoleID(roleID)
	return o
}

// SetRoleID adds the roleId to the delete role binding params
func (o *DeleteRoleBindingParams) SetRoleID(roleID string) {
	o.RoleID = roleID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRoleBindingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param binding_id
	if err := r.SetPathParam("binding_id", o.BindingID); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.Dc); err != nil {
		return err
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	// path param role_id
	if err := r.SetPathParam("role_id", o.RoleID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
