{
 "title": "Cortex / Writes",
 "tags": [ "cortex" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cortex_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Writes dashboard description",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<p>\n  This dashboard shows various health metrics for the Cortex write path.\n  It is broken into sections for each service on the write path,\n  and organized by the order in which the write request flows.\n  <br/>\n  Incoming metrics data travels from the gateway → distributor → ingester.\n  <br/>\n  For each service, there are 3 panels showing\n  (1) requests per second to that service,\n  (2) average, median, and p99 latency of requests to that service, and\n  (3) p99 latency of requests to each instance of that service.\n</p>\n<p>\n  It also includes metrics for the key-value (KV) stores used to manage\n  the high-availability tracker and the ingesters.\n</p>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Samples / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster_namespace_job:cortex_distributor_received_samples:rate5m{ job=\"pods\"})"
    }
   ]
  },
  {
   "title": "Active Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_memory_series{ job=\"pods\"}\n/ on(cluster, namespace) group_left\nmax by (cluster, namespace) (cortex_distributor_replication_factor{ job=\"pods\"}))\n"
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(user) (cortex_ingester_active_series{ job=\"pods\"}))"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{ job=\"pods\", route=~\"api_(v1|prom)_push\"}[5m]))"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_request_duration_seconds_count{ job=\"pods\", route=~\"api_(v1|prom)_push\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=~\"api_(v1|prom)_push\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=~\"api_(v1|prom)_push\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:cortex_request_duration_seconds_sum:sum_rate{ job=\"pods\", route=~\"api_(v1|prom)_push\"}) / sum(cluster_job_route:cortex_request_duration_seconds_count:sum_rate{ job=\"pods\", route=~\"api_(v1|prom)_push\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per pod p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate(cortex_request_duration_seconds_bucket{ job=\"pods\", route=~\"api_(v1|prom)_push\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_request_duration_seconds_count{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:cortex_request_duration_seconds_sum:sum_rate{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"}) / sum(cluster_job_route:cortex_request_duration_seconds_count:sum_rate{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per pod p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate(cortex_request_duration_seconds_bucket{ job=\"pods\", route=~\"/distributor.Distributor/Push|/httpgrpc.*|api_(v1|prom)_push\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Key-value store for high-availability (HA) deduplication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_kv_request_duration_seconds_count{ job=\"pods\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:cortex_kv_request_duration_seconds_bucket:sum_rate{ job=\"pods\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job:cortex_kv_request_duration_seconds_bucket:sum_rate{ job=\"pods\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job:cortex_kv_request_duration_seconds_sum:sum_rate{ job=\"pods\"}) / sum(cluster_job:cortex_kv_request_duration_seconds_count:sum_rate{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_request_duration_seconds_count{ job=\"pods\",route=\"/cortex.Ingester/Push\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=\"/cortex.Ingester/Push\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:cortex_request_duration_seconds_bucket:sum_rate{ job=\"pods\", route=\"/cortex.Ingester/Push\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:cortex_request_duration_seconds_sum:sum_rate{ job=\"pods\", route=\"/cortex.Ingester/Push\"}) / sum(cluster_job_route:cortex_request_duration_seconds_count:sum_rate{ job=\"pods\", route=\"/cortex.Ingester/Push\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per pod p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, pod) (rate(cortex_request_duration_seconds_bucket{ job=\"pods\", route=\"/cortex.Ingester/Push\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Key-value store for the ingesters ring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(cortex_kv_request_duration_seconds_count{ job=\"pods\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:cortex_kv_request_duration_seconds_bucket:sum_rate{ job=\"pods\"})) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job:cortex_kv_request_duration_seconds_bucket:sum_rate{ job=\"pods\"})) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job:cortex_kv_request_duration_seconds_sum:sum_rate{ job=\"pods\"}) / sum(cluster_job:cortex_kv_request_duration_seconds_count:sum_rate{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Ingester - Blocks storage - Shipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uploaded blocks / sec",
   "type": "timeseries",
   "description": "### Uploaded blocks / sec\nThe rate of blocks being uploaded from the ingesters\nto object storage.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_shipper_uploads_total{ job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_ingester_shipper_upload_failures_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_ingester_shipper_upload_failures_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Upload latency",
   "type": "timeseries",
   "description": "### Upload latency\nThe average, median (50th percentile), and 99th percentile time\nthe ingesters take to upload blocks to object storage.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{ job=\"pods\",component=\"ingester\",operation=\"upload\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(thanos_objstore_bucket_operation_duration_seconds_bucket{ job=\"pods\",component=\"ingester\",operation=\"upload\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(thanos_objstore_bucket_operation_duration_seconds_sum{ job=\"pods\",component=\"ingester\",operation=\"upload\"}[$__rate_interval])) * 1e3 / sum(rate(thanos_objstore_bucket_operation_duration_seconds_count{ job=\"pods\",component=\"ingester\",operation=\"upload\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Ingester - Blocks storage - TSDB Head",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Compactions / sec",
   "type": "timeseries",
   "description": "### Compactions per second\nIngesters maintain a local TSDB per-tenant on disk. Each TSDB maintains a head block for each\nactive time series; these blocks get periodically compacted (by default, every 2h).\nThis panel shows the rate of compaction operations across all TSDBs on all ingesters.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_tsdb_compactions_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_ingester_tsdb_compactions_failed_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Compactions latency",
   "type": "timeseries",
   "description": "### Compaction latency\nThe average, median (50th percentile), and 99th percentile time ingesters take to compact TSDB head blocks\non the local filesystem.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_ingester_tsdb_compaction_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_ingester_tsdb_compaction_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_ingester_tsdb_compaction_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_ingester_tsdb_compaction_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Ingester - Blocks storage - TSDB write ahead log (WAL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL truncations / sec",
   "type": "timeseries",
   "description": "### WAL truncations per second\nThe WAL is truncated each time a new TSDB block is written. This panel measures the rate of\ntruncations.\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_tsdb_wal_truncations_total{ job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_ingester_tsdb_wal_truncations_failed_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_ingester_tsdb_wal_truncations_failed_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Checkpoints created / sec",
   "type": "timeseries",
   "description": "### Checkpoints created per second\nCheckpoints are created as part of the WAL truncation process.\nThis metric measures the rate of checkpoint creation.\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_tsdb_checkpoint_creations_total{ job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_ingester_tsdb_checkpoint_creations_failed_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_ingester_tsdb_checkpoint_creations_failed_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "WAL truncations latency (includes checkpointing)",
   "type": "timeseries",
   "description": "### WAL truncations latency (including checkpointing)\nAverage time taken to perform a full WAL truncation,\nincluding the time taken for the checkpointing to complete.\n\n",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_tsdb_wal_truncate_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) / sum(rate(cortex_ingester_tsdb_wal_truncate_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Corruptions / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_wal_corruptions_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "WAL"
    },
    {
     "expr": "sum(rate(cortex_ingester_tsdb_mmap_chunk_corruptions_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "mmap-ed chunks"
    }
   ]
  }
 ]
}