{
 "title": "Cortex / Queries",
 "tags": [ "cortex" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(cortex_build_info,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_query_frontend_queue_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_query_frontend_queue_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_query_frontend_queue_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_query_frontend_queue_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_query_frontend_retries_bucket{job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_query_frontend_retries_bucket{job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_query_frontend_retries_sum{job=\"pods\"}[$__rate_interval])) * 1 / sum(rate(cortex_query_frontend_retries_count{job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cortex_query_frontend_queue_length{ job=\"pods\"}",
     "legendFormat": "{{cluster}} / {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Query Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_query_scheduler_queue_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_query_scheduler_queue_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_query_scheduler_queue_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_query_scheduler_queue_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cortex_query_scheduler_queue_length{ job=\"pods\"}",
     "legendFormat": "{{cluster}} / {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "Query Frontend - Query Splitting and Results Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Intervals per Query",
   "type": "timeseries",
   "description": "### Intervals per Query\nThe average number of split queries (partitioned by time) executed a single input query.\n\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_frontend_split_queries_total{ job=\"pods\"}[1m])) / sum(rate(cortex_frontend_query_range_duration_seconds_count{ job=\"pods\", method=\"split_by_interval\"}[1m]))",
     "legendFormat": "splitting rate"
    }
   ]
  },
  {
   "title": "Results Cache Hit %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_cache_hits{name=~\"frontend.+\",  job=\"pods\"}[1m])) / sum(rate(cortex_cache_fetched_keys{name=~\"frontend.+\",  job=\"pods\"}[1m])) or\nsum(rate(cortex_cache_hits_total{name=~\"frontend.+\",  job=\"pods\"}[1m])) / sum(rate(cortex_cache_fetched_keys_total{name=~\"frontend.+\",  job=\"pods\"}[1m]))\n",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Results Cache misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_cache_fetched_keys{name=~\"frontend.+\",  job=\"pods\"}[1m])) - sum(rate(cortex_cache_hits{name=~\"frontend.+\",  job=\"pods\"}[1m])) or\nsum(rate(cortex_cache_fetched_keys_total{name=~\"frontend.+\",  job=\"pods\"}[1m])) - sum(rate(cortex_cache_hits_total{name=~\"frontend.+\",  job=\"pods\"}[1m]))\n",
     "legendFormat": "Miss Rate"
    }
   ]
  },
  {
   "title": "Query Frontend - Query sharding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sharded Queries Ratio",
   "type": "timeseries",
   "description": "### Sharded Queries Ratio\nThe % of queries that have been successfully rewritten and executed in a shardable way.\nThis panel takes in account only type of queries which are supported by query sharding (eg. range queries).\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_frontend_query_sharding_rewrites_succeeded_total{ job=\"pods\"}[$__rate_interval])) /\nsum(rate(cortex_frontend_query_sharding_rewrites_attempted_total{ job=\"pods\"}[$__rate_interval]))\n",
     "legendFormat": "sharded queries ratio"
    }
   ]
  },
  {
   "title": "Number of Sharded Queries per Query",
   "type": "timeseries",
   "description": "### Number of Sharded Queries per Query\nHow many sharded queries have been executed for a single input query. It tracks only queries which have\nbeen successfully rewritten in a shardable way.\n\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_frontend_sharded_queries_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_frontend_sharded_queries_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_frontend_sharded_queries_per_query_sum{ job=\"pods\"}[$__rate_interval])) * 1 / sum(rate(cortex_frontend_sharded_queries_per_query_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Stages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (slice) (prometheus_engine_query_duration_seconds{quantile=\"0.9\", job=\"pods\"}) * 1e3",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Chunk cache misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_cache_fetched_keys{ job=\"pods\",name=\"chunksmemcache\"}[1m])) - sum(rate(cortex_cache_hits{ job=\"pods\",name=\"chunksmemcache\"}[1m])) or\nsum(rate(cortex_cache_fetched_keys_total{ job=\"pods\",name=\"chunksmemcache\"}[1m])) - sum(rate(cortex_cache_hits_total{ job=\"pods\",name=\"chunksmemcache\"}[1m]))\n",
     "legendFormat": "Hit rate"
    }
   ]
  },
  {
   "title": "Chunk cache corruptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_cache_corrupt_chunks_total{ job=\"pods\"}[1m]))",
     "legendFormat": "Corrupt chunks"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Series per Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:cortex_ingester_queried_series_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job:cortex_ingester_queried_series_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1 * sum(cluster_job:cortex_ingester_queried_series_sum:sum_rate{ job=\"pods\"}) / sum(cluster_job:cortex_ingester_queried_series_count:sum_rate{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Chunks per Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:cortex_ingester_queried_chunks_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job:cortex_ingester_queried_chunks_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1 * sum(cluster_job:cortex_ingester_queried_chunks_sum:sum_rate{ job=\"pods\"}) / sum(cluster_job:cortex_ingester_queried_chunks_count:sum_rate{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Samples per Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:cortex_ingester_queried_samples_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job:cortex_ingester_queried_samples_bucket:sum_rate{ job=\"pods\"})) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "1 * sum(cluster_job:cortex_ingester_queried_samples_sum:sum_rate{ job=\"pods\"}) / sum(cluster_job:cortex_ingester_queried_samples_count:sum_rate{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Querier - Blocks storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of store-gateways hit per Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_querier_storegateway_instances_hit_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_querier_storegateway_instances_hit_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_querier_storegateway_instances_hit_per_query_sum{ job=\"pods\"}[$__rate_interval])) * 1 / sum(rate(cortex_querier_storegateway_instances_hit_per_query_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Refetches of missing blocks per Query",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_querier_storegateway_refetches_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_querier_storegateway_refetches_per_query_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_querier_storegateway_refetches_per_query_sum{ job=\"pods\"}[$__rate_interval])) * 1 / sum(rate(cortex_querier_storegateway_refetches_per_query_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Consistency checks failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_querier_blocks_consistency_checks_failed_total{ job=\"pods\"}[1m])) / sum(rate(cortex_querier_blocks_consistency_checks_total{ job=\"pods\"}[1m]))",
     "legendFormat": "Failure Rate"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bucket indexes loaded (per querier)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(cortex_bucket_index_loaded{ job=\"pods\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(cortex_bucket_index_loaded{ job=\"pods\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(cortex_bucket_index_loaded{ job=\"pods\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Bucket indexes load / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_index_loads_total{ job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_bucket_index_load_failures_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_bucket_index_load_failures_total{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Bucket indexes load latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bucket_index_load_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_bucket_index_load_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_bucket_index_load_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_bucket_index_load_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Store-gateway - Blocks storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks queried / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_store_series_blocks_queried_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Data fetched / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(data_type) (rate(cortex_bucket_store_series_data_fetched_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Data touched / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(data_type) (rate(cortex_bucket_store_series_data_touched_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Series fetch duration (per request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bucket_store_series_get_all_duration_seconds_bucket{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_bucket_store_series_get_all_duration_seconds_bucket{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_bucket_store_series_get_all_duration_seconds_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_bucket_store_series_get_all_duration_seconds_count{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Series merge duration (per request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bucket_store_series_merge_duration_seconds_bucket{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_bucket_store_series_merge_duration_seconds_bucket{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_bucket_store_series_merge_duration_seconds_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_bucket_store_series_merge_duration_seconds_count{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Series returned (per request)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_store_series_result_series_sum{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) / sum(rate(cortex_bucket_store_series_result_series_count{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "avg series returned"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks currently loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cortex_bucket_store_blocks_loaded{component=\"store-gateway\", job=\"pods\"}) without (user)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks loaded / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_store_block_loads_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_bucket_store_block_load_failures_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_bucket_store_block_load_failures_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Blocks dropped / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_store_block_drops_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval])) - sum(rate(cortex_bucket_store_block_drop_failures_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "successful"
    },
    {
     "expr": "sum(rate(cortex_bucket_store_block_drop_failures_total{component=\"store-gateway\", job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lazy loaded index-headers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cortex_bucket_store_indexheader_lazy_load_total{ job=\"pods\"} - cortex_bucket_store_indexheader_lazy_unload_total{ job=\"pods\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Index-header lazy load duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cortex_bucket_store_indexheader_lazy_load_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(cortex_bucket_store_indexheader_lazy_load_duration_seconds_bucket{ job=\"pods\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(cortex_bucket_store_indexheader_lazy_load_duration_seconds_sum{ job=\"pods\"}[$__rate_interval])) * 1e3 / sum(rate(cortex_bucket_store_indexheader_lazy_load_duration_seconds_count{ job=\"pods\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Series hash cache hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cortex_bucket_store_series_hash_cache_hits_total{ job=\"pods\"}[$__rate_interval]))\n/\nsum(rate(cortex_bucket_store_series_hash_cache_requests_total{ job=\"pods\"}[$__rate_interval]))\n",
     "legendFormat": "hit ratio"
    }
   ]
  }
 ]
}