{
 "title": "MLA components",
 "description": "User Cluster MLA Deployments/Statefulset Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "deployment_namespace", "label": "Namespace", "query": "mla" },
   {
    "name": "deployment_name",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$deployment_namespace\"}, deployment)"
    }
   },
   {
    "name": "statefulset_name",
    "label": "Satefulset",
    "query": {
     "query": "label_values(kube_statefulset_metadata_generation{namespace=~\"$deployment_namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=~\"$deployment_namespace\",pod=~\"^$deployment_name|$statefulset_name.*$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$deployment_namespace\",pod=~\"^$deployment_name|$statefulset_name.*$\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"^$deployment_name|$statefulset_name.*$\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"^$deployment_name|$statefulset_name.*$.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(max(kube_deployment_spec_replicas{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) + sum(max(kube_statefulset_replicas{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(min(kube_deployment_status_replicas_available{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) + sum(min(kube_statefulset_status_replicas_current{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max(kube_deployment_status_replicas{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) + sum(max(kube_statefulset_status_replicas_current{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(min(kube_deployment_status_replicas_available{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) + sum(min(kube_statefulset_status_replicas_ready{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(max(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) +\n(sum(max(kube_statefulset_replicas{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) - sum(min(kube_statefulset_status_replicas_ready{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)))",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "sum(min(kube_deployment_status_replicas_updated{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) + sum(min(kube_statefulset_status_replicas_updated{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(max(kube_deployment_spec_replicas{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)) +\nsum(max(kube_statefulset_replicas{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod))",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "$deployment_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "deployment_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$deployment_namespace\",pod=~\"$deployment_name.*\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"$deployment_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=~\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_observed_generation{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_deployment_metadata_generation{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_deployment_status_replicas{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_deployment_status_replicas_unavailable{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "min(kube_deployment_status_replicas_updated{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    },
    {
     "expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    }
   ]
  },
  {
   "title": "$statefulset_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "statefulset_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$deployment_namespace\",pod=~\"$statefulset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$deployment_namespace\",pod=~\"$statefulset_name.*\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"$statefulset_name.*\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$deployment_namespace\",pod=~\"$statefulset_name.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Available Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_statefulset_status_replicas_current{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "max(kube_statefulset_replicas{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod) - min(kube_statefulset_status_replicas_ready{statefulset=~\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    },
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$statefulset_name\",namespace=~\"$deployment_namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    }
   ]
  }
 ]
}