{
 "title": "Kubelets",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node_name)"
    }
   },
   {
    "name": "runtime_operations",
    "query": {
     "query": "label_values(kubelet_runtime_operations_duration_seconds_bucket, operation_type)"
    }
   },
   {
    "name": "pod_worker_operations",
    "query": {
     "query": "label_values(kubelet_pod_worker_duration_seconds_bucket, operation_type)"
    }
   },
   {
    "name": "cgroup_manager_operations",
    "query": {
     "query": "label_values(kubelet_cgroup_manager_duration_seconds_bucket, operation_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by HTTP Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubelet\",instance=\"$node\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Runtime Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_runtime_operations_errors_total{instance=\"$node\"}[5m])",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_duration_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  { "title": "Pod Worker Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$pod_worker_operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "repeat": "pod_worker_operations",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_pod_worker_duration_seconds_bucket{instance=\"$node\",operation_type=\"$pod_worker_operations\"}[5m])) by (instance, le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kubelet_pod_worker_duration_seconds_bucket{instance=\"$node\",operation_type=\"$pod_worker_operations\"}[5m])) by (instance, le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "cgroup Manager Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$cgroup_manager_operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "repeat": "cgroup_manager_operations",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{instance=\"$node\",operation_type=\"$cgroup_manager_operations\"}[5m])) by (instance, le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kubelet_cgroup_manager_duration_seconds_bucket{instance=\"$node\",operation_type=\"$cgroup_manager_operations\"}[5m])) by (instance, le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "Runtime Operations Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$runtime_operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "repeat": "runtime_operations",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=\"$node\",operation_type=\"$runtime_operations\"}[5m])) by (instance, le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=\"$node\",operation_type=\"$runtime_operations\"}[5m])) by (instance, le))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "PLEG Relist Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Relists",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=\"$node\"}[5m])) by (instance, le))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(kubelet_runtime_operations_duration_seconds_bucket{instance=\"$node\"}[5m])) by (instance, le))",
     "legendFormat": "90th percentile"
    }
   ]
  }
 ]
}