{
 "title": "Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_load1{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "CPU Utilization per Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[5m]) * 100)",
     "legendFormat": "core {{ cpu }}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[2m]) * 100))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sum by (cpu) (rate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", node_name=\"$node\"}[2m]) * 100))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{app=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_MemFree_bytes{app=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_Buffers_bytes{app=\"node-exporter\", node_name=\"$node\"}\n  - node_memory_Cached_bytes{app=\"node-exporter\", node_name=\"$node\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{app=\"node-exporter\", node_name=\"$node\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{app=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_MemFree_bytes{app=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_Buffers_bytes{app=\"node-exporter\", node_name=\"$node\"}\n    - node_memory_Cached_bytes{app=\"node-exporter\", node_name=\"$node\"}\n    )\n    / node_memory_MemTotal_bytes{app=\"node-exporter\", node_name=\"$node\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  node_filesystem_files{app=\"node-exporter\", node_name=\"$node\"}\n  - node_filesystem_files_free{app=\"node-exporter\", node_name=\"$node\"}\n)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Current Inode Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_filesystem_files{app=\"node-exporter\", node_name=\"$node\"}\n    - node_filesystem_files_free{app=\"node-exporter\", node_name=\"$node\"}\n    )\n    / node_filesystem_files{app=\"node-exporter\", node_name=\"$node\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{app=\"node-exporter\", node_name=\"$node\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{app=\"node-exporter\", node_name=\"$node\"}[2m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{app=\"node-exporter\", node_name=\"$node\", device!~\"lo\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{app=\"node-exporter\", node_name=\"$node\", device!~\"lo\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{app=\"node-exporter\",  node_name=\"$node\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max by (device) (node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=\"$node\"} / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=\"$node\"}))",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}