{
 "title": "Nodes Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(node_boot_time_seconds{app.kubernetes.io/name=\"node-exporter\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (node_name) (100 - (rate(node_cpu_seconds_total{app.kubernetes.io/name=\"node-exporter\", mode=\"idle\", node_name=~\"$nodes\"}[2m]) * 100))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (100 - (rate(node_cpu_seconds_total{app.kubernetes.io/name=\"node-exporter\", mode=\"idle\", node_name=~\"$nodes\"}[2m]) * 100))"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (node_name) (\n  node_memory_MemTotal_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_MemFree_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_Buffers_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n  - node_memory_Cached_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n)\n",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  (\n    sum(\n      node_memory_MemTotal_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_MemFree_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_Buffers_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n    - node_memory_Cached_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n    )\n    /\n    sum(\n      node_memory_MemTotal_bytes{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}\n    )\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_network_receive_bytes_total{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_network_transmit_bytes_total{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_read_bytes_total{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_written_bytes_total{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (node_name) (rate(node_disk_io_time_seconds_total{app.kubernetes.io/name=\"node-exporter\", node_name=~\"$nodes\"}[2m]))",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by (node_name) (node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=~\"$nodes\"}) / sum by (node_name) (node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\", node_name=~\"$nodes\"})",
     "legendFormat": "{{ node_name }}"
    }
   ]
  }
 ]
}