{
 "title": "etcd",
 "description": "etcd metrics",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "User Cluster",
    "query": "label_values(job:etcd_server_has_leader:sum, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "job:etcd_server_has_leader:sum{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:process_cpu_seconds_total:rate5m{cluster=\"$cluster\",instance=~\"etcd-.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "job:process_resident_memory_bytes:clone{cluster=\"$cluster\",instance=~\"etcd-.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:process_open_fds:clone{cluster=\"$cluster\",instance=~\"etcd-.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_db_total_size_in_bytes:clone{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Sync Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "job:etcd_disk_wal_fsync_duration_seconds_bucket:99percentile{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} WAL fsync"
    },
    {
     "expr": "job:etcd_disk_backend_commit_duration_seconds_bucket:99percentile{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} DB fsync"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "job:etcd_network_client_grpc_received_bytes_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "job:etcd_network_client_grpc_sent_bytes_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "job:etcd_network_peer_received_bytes_total:rate5msum{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peer Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "job:etcd_network_peer_sent_bytes_total:rate5msum{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Proposals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_server_proposals_failed_total:rate5msum{cluster=\"$cluster\"}",
     "legendFormat": "Proposal Failure Rate"
    },
    {
     "expr": "job:etcd_server_proposals_pending:sum{cluster=\"$cluster\"}",
     "legendFormat": "Proposal Pending Total"
    },
    {
     "expr": "job:etcd_server_proposals_committed_total:rate5msum{cluster=\"$cluster\"}",
     "legendFormat": "Proposal Commit Rate"
    },
    {
     "expr": "job:etcd_server_proposals_applied_total:rate5msum{cluster=\"$cluster\"}",
     "legendFormat": "Proposal Apply Rate"
    }
   ]
  },
  {
   "title": "Total Leader Elections Per Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_server_leader_changes_seen_total:changes1d{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_txn_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PUT Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_put_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RANGE Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_range_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DELETE Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_delete_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_mvcc_keys_total:clone{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_store_reads_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_store_writes_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}} {{action}} ops"
    }
   ]
  },
  {
   "title": "Expires",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "job:etcd_debugging_store_expires_total:rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}