{
 "title": "Kubelets",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, node_name)"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by HTTP Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubelet\",instance=\"$node\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Runtime Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kubelet_runtime_operations_errors{instance=\"$node\"}[5m])",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  { "title": "Pod Worker Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"create\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"create\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"update\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"update\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Syncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"sync\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"sync\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"kill\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pod_worker_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pod_worker_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"kill\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "cgroup Manager Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"create\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"create\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"update\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"update\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Syncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"sync\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"sync\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"kill\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_cgroup_manager_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"kill\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "Runtime Operations Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"create\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"create\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"update\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"update\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Syncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"sync\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"sync\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"kill\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_runtime_operations_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_runtime_operations_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"kill\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  { "title": "PLEG Relist Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Creates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"create\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"create\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"create\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"update\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"update\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"update\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Syncs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"sync\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"sync\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"sync\"}",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Kills",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.99\",operation_type=\"kill\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "max(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min(kubelet_pleg_relist_latency_microseconds{instance=\"$node\",operation_type=\"kill\"})",
     "legendFormat": "min"
    },
    {
     "expr": "kubelet_pleg_relist_latency_microseconds{instance=\"$node\",quantile=\"0.9\",operation_type=\"kill\"}",
     "legendFormat": "90th percentile"
    }
   ]
  }
 ]
}