{
 "title": "Kubelets Overview",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_boot_time_seconds, node_name)"
   },
   { "name": "operations", "label": "Operations", "query": "create,update,sync,kill" }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by HTTP Status (Success)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubelet\",instance=~\"$node\",code!~\"5..\",code!=\"<error>\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Request Rate by HTTP Status (Errors)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kubelet\",instance=~\"$node\",code=~\"(5..|<error>)\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Runtime Error Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_errors{instance=~\"$node\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Operation Latencies (90th Percentiles)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Pod Worker Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pod_worker_latency_microseconds{instance=~\"$node\",quantile=\"0.9\",operation_type=~\"$operations\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "cgroup Manager Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_cgroup_manager_latency_microseconds{instance=~\"$node\",quantile=\"0.9\",operation_type=~\"$operations\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Runtime Operations Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_latency_microseconds{instance=~\"$node\",quantile=\"0.9\",operation_type=~\"$operations\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "PLEG Relist Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_latency_microseconds{instance=~\"$node\",quantile=\"0.9\",operation_type=~\"$operations\"}[5m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Request Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "repeat": "node",
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  },
  {
   "title": "$node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(rest_client_request_latency_seconds_bucket{job=\"kubelet\",instance=\"$node\"}[5m])) by (le)",
     "legendFormat": "{{ le }} s"
    }
   ]
  }
 ]
}