{
 "title": "Nodes",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{app=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "CPU Utilization per Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[5m]) * 100)",
     "legendFormat": "core {{ cpu }}"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[2m]) * 100))",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg (sum by (cpu) (irate(node_cpu_seconds_total{app=\"node-exporter\", mode!=\"idle\", instance=\"$instance\"}[2m]) * 100))"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{app=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_MemFree_bytes{app=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_Buffers_bytes{app=\"node-exporter\", instance=\"$instance\"}\n  - node_memory_Cached_bytes{app=\"node-exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{app=\"node-exporter\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{app=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_MemFree_bytes{app=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_Buffers_bytes{app=\"node-exporter\", instance=\"$instance\"}\n    - node_memory_Cached_bytes{app=\"node-exporter\", instance=\"$instance\"}\n    )\n    / node_memory_MemTotal_bytes{app=\"node-exporter\", instance=\"$instance\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Inode Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_filesystem_files{app=\"node-exporter\", instance=\"$instance\"}\n  - node_filesystem_files_free{app=\"node-exporter\", instance=\"$instance\"}\n)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Current Inode Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_filesystem_files{app=\"node-exporter\", instance=\"$instance\"}\n    - node_filesystem_files_free{app=\"node-exporter\", instance=\"$instance\"}\n    )\n    / node_filesystem_files{app=\"node-exporter\", instance=\"$instance\"}\n  ) * 100)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{app=\"node-exporter\", instance=\"$instance\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{app=\"node-exporter\", instance=\"$instance\"}[2m]))",
     "legendFormat": "written"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{app=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[2m]))",
     "legendFormat": "received"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{app=\"node-exporter\", instance=\"$instance\", device!~\"lo\"}[2m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{app=\"node-exporter\",  instance=\"$instance\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (max by (device) (node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\",instance=\"$instance\"} / node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\",instance=\"$instance\"}))",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}