{
 "title": "Volumes",
 "time": { "from": "<< defaultRange | toJson >>", "to": "now" },
 "refresh": "<< refresh | default `30s` | toJson >>",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kubelet_volume_stats_used_bytes{ [[ volumeDashboardNamespaceFilter ]] }, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kubelet_volume_stats_used_bytes) / sum(kubelet_volume_stats_capacity_bytes)"
    }
   ]
  },
  {
   "title": "Total Disk Capacity",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes)"
    }
   ]
  },
  {
   "title": "Total Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes)"
    }
   ]
  },
  {
   "title": "Total Used Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes)"
    }
   ]
  },
  { "title": "$namespace namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "namespace" },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": " sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Disk Usages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})"
    }
   ]
  }
 ]
}