# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

loki:
  fullnameOverride: loki

  tracing:
    enabled: false

  loki:
    auth_enabled: false
    ingester:
      chunk_encoding: snappy
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 2
    memberlistConfig:
      # Force empty memberlist since we're running in single binary mode with 1 replica.
      # This is instead of the single member loki-memberlist.logging.svc.cluster.local.
      # Otherwise Loki logs an error at startup: "failed to fast-join the memberlist".
      join_members: []
    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 144h
      retention_period: 720h
    schemaConfig:
      configs:
      - from: 2022-01-11
        store: boltdb-shipper
        object_store: filesystem
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
      - from: 2026-05-13
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
    storage:
      type: filesystem
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    storage_config:
      boltdb:
        directory: /var/loki/index
      filesystem:
        directory: /var/loki/chunks
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-shipper/active
        cache_location: /var/loki/tsdb-shipper/cache
        cache_ttl: 24h
    chunk_store_config:
      max_look_back_period: 720h
    compactor:
      working_directory: /var/loki/tsdb-shipper-compactor
      delete_request_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 10m
      retention_delete_worker_count: 150
      max_compaction_parallelism: 10

  tableManager:
    retention_deletes_enabled: true
    retention_period: 720h

  deploymentMode: SingleBinary
  singleBinary:
    replicas: 1

    persistence:
      enabled: true
      size: 15Gi
      storageClass: kubermatic-fast
      enableStatefulSetAutoDeletePVC: false

    resources:
      limits:
        cpu: "1"
        # Increased based on real world usage where Loki crashes on longer time periods
        memory: 1Gi
      requests:
        cpu: 300m
        memory: 256Mi
    extraEnv:
      # Keep a little bit lower than memory limits
      - name: GOMEMLIMIT
        value: 750MiB

    podLabels: {}
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "3100"
      cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: tmp

  chunksCache:
    # if enabled, the chunks cache is served via a memcached StatefulSet
    enabled: false

  resultsCache:
    # if enabled, the results cache is served via a memcached StatefulSet
    enabled: false

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  gateway:
    enabled: false

  test:
    enabled: false

  lokiCanary:
    enabled: false
