{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,5m,10m,30m,60m" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(prometheus_build_info, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Currently Down",
   "type": "table",
   "description": "Servers which are DOWN RIGHT NOW!",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"pods\",pod=~\"$pod\"} < 1"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "singlestat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=\"pods\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=\"pods\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Missed Iterations",
   "type": "singlestat",
   "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_rule_group_iterations_missed_total{job=\"pods\",pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Tardy Scrapes",
   "type": "singlestat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"pods\",pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reload Failures",
   "type": "singlestat",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes",
   "type": "singlestat",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"pods\",pod=~\"$pod\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"pods\",pod=~\"$pod\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"pods\",job=\"pods\",pod=~\"$pod\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\"}[$interval])) "
    }
   ]
  },
  {
   "title": "Failures and Errors",
   "type": "graph",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Failed Connections"
    },
    {
     "expr": "sum(increase(prometheus_rule_group_iterations_missed_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Missed Iterations"
    },
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Evaluation"
    },
    {
     "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Azure Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Consul RPC"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "DNS Lookup"
    },
    {
     "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "EC2 Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "GCE Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Marathon Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Openstack Refresh"
    },
    {
     "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Triton Refresh"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Sample Limit"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Duplicate Timestamp"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Timestamp Out of Bounds"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Sample Out of Order"
    },
    {
     "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Zookeeper"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "TSDB Compactions"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Series Not Found"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{job=\"pods\",pod=~\"$pod\"}[$interval])) > 0",
     "legendFormat": "Reload"
    }
   ]
  },
  {
   "title": "Upness (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Up" }
   ],
   "targets": [
    {
     "expr": "min(up{job=\"pods\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Chunks" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Series Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Series" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Series Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_created_total{job=\"pods\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_removed_total{job=\"pods\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "removed"
    }
   ]
  },
  {
   "title": "Appended Samples per Second",
   "type": "graph",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Samples / Second" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=\"pods\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Scrape Sync Rate",
   "type": "graph",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Syncs" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_scrape_pool_sync_total{job=\"pods\",pod=~\"$pod\"}[$interval])) by (scrape_job)",
     "legendFormat": "{{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "graph",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms", "label": "Sync Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=\"pods\",pod=~\"$pod\"}[$interval])) by (scrape_job) * 1000",
     "legendFormat": "{{ scrape_job }}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "graph",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short", "label": "Scrapes" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{pod=~\"$pod\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{pod=~\"$pod\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{pod=~\"$pod\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{pod=~\"$pod\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  {
   "title": "Average Rule Evaluation Duration",
   "type": "graph",
   "description": "The duration of rule group evaluations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_evaluation_duration_seconds_sum{job=\"pods\",pod=~\"$pod\"}[$interval]) / rate(prometheus_rule_evaluation_duration_seconds_count{job=\"pods\",pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_count[$interval])) by (handler) > 0",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_query_duration_seconds_sum{pod=~\"$pod\"}[$interval])) by (slice)",
     "legendFormat": "{{ slice }}"
    }
   ]
  },
  {
   "title": "Rule Evaluator Iterations",
   "type": "graph",
   "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Iterations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_total{job=\"pods\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(prometheus_rule_group_iterations_missed_total{job=\"pods\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "Missed"
    }
   ]
  },
  {
   "title": "Notifications Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "Notifications" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_notifications_sent_total[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Minutes Since Successful Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s", "label": "Minutes" }
   ],
   "targets": [
    {
     "expr": "sum((time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"pods\",pod=~\"$pod\"})) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Success" }
   ],
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=\"pods\",pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "graph",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=\"pods\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}