{
 "title": "Thanos Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "monitoring" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gPRC (Unary) Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": " {{ grpc_code }}"
    }
   ]
  },
  {
   "title": "gPRC (Unary) Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",job=\"thanos-sidecar\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "gPRC (Unary) Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\",namespace=\"$namespace\",job=\"thanos-sidecar\"}[$interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "gPRC (Unary) Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{namespace=\"$namespace\",app_kubernetes_io_name=\"thanos-store\",grpc_type=\"unary\"}[$interval])) by (grpc_code)",
     "legendFormat": "{{ grpc_code }}"
    }
   ]
  },
  {
   "title": "gPRC (Unary) Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code!=\"OK\",namespace=\"$namespace\",app_kubernetes_io_name=\"thanos-store\",grpc_type=\"unary\"}[$interval])) / sum(rate(grpc_server_started_total{namespace=\"$namespace\",app_kubernetes_io_name=\"thanos-store\",grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "gRPC Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{grpc_type=\"unary\",namespace=\"$namespace\",grpc_service=\"thanos.Store\"}[$interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Compaction Rate",
   "type": "graph",
   "description": "Shows rate of execution for compactions against blocks that are stored in the bucket by compaction group.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "compactions"
    }
   ]
  },
  {
   "title": "Compaction Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of executed compactions against blocks that are stored in the bucket.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(thanos_compact_group_compactions_failures_total{namespace=\"$namespace\",job=\"pods\"}[$interval])) / sum(rate(thanos_compact_group_compactions_total{namespace=\"$namespace\",job=\"pods\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "Instant Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Requests Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\",code!~\"2..\"}[$interval])) / sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query\"}[$interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Range Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Requests Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval]),\"status_code\", \"${1}xx\", \"code\", \"([0-9])..\")) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the the total number of handled requests against /query_range.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\",code!~\"2..\"}[$interval])) / sum(rate(http_requests_total{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Latency 99th Percentile",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\",job=\"pods\",handler=\"query_range\"}[$interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}