// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	scheme "k8c.io/kubermatic/v2/pkg/crd/client/clientset/versioned/scheme"
	v1 "k8c.io/kubermatic/v2/pkg/crd/kubermatic/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WhitelistedRegistriesGetter has a method to return a WhitelistedRegistryInterface.
// A group's client should implement this interface.
type WhitelistedRegistriesGetter interface {
	WhitelistedRegistries() WhitelistedRegistryInterface
}

// WhitelistedRegistryInterface has methods to work with WhitelistedRegistry resources.
type WhitelistedRegistryInterface interface {
	Create(ctx context.Context, whitelistedRegistry *v1.WhitelistedRegistry, opts metav1.CreateOptions) (*v1.WhitelistedRegistry, error)
	Update(ctx context.Context, whitelistedRegistry *v1.WhitelistedRegistry, opts metav1.UpdateOptions) (*v1.WhitelistedRegistry, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.WhitelistedRegistry, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.WhitelistedRegistryList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.WhitelistedRegistry, err error)
	WhitelistedRegistryExpansion
}

// whitelistedRegistries implements WhitelistedRegistryInterface
type whitelistedRegistries struct {
	client rest.Interface
}

// newWhitelistedRegistries returns a WhitelistedRegistries
func newWhitelistedRegistries(c *KubermaticV1Client) *whitelistedRegistries {
	return &whitelistedRegistries{
		client: c.RESTClient(),
	}
}

// Get takes name of the whitelistedRegistry, and returns the corresponding whitelistedRegistry object, and an error if there is any.
func (c *whitelistedRegistries) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.WhitelistedRegistry, err error) {
	result = &v1.WhitelistedRegistry{}
	err = c.client.Get().
		Resource("whitelistedregistries").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WhitelistedRegistries that match those selectors.
func (c *whitelistedRegistries) List(ctx context.Context, opts metav1.ListOptions) (result *v1.WhitelistedRegistryList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.WhitelistedRegistryList{}
	err = c.client.Get().
		Resource("whitelistedregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested whitelistedRegistries.
func (c *whitelistedRegistries) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("whitelistedregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a whitelistedRegistry and creates it.  Returns the server's representation of the whitelistedRegistry, and an error, if there is any.
func (c *whitelistedRegistries) Create(ctx context.Context, whitelistedRegistry *v1.WhitelistedRegistry, opts metav1.CreateOptions) (result *v1.WhitelistedRegistry, err error) {
	result = &v1.WhitelistedRegistry{}
	err = c.client.Post().
		Resource("whitelistedregistries").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(whitelistedRegistry).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a whitelistedRegistry and updates it. Returns the server's representation of the whitelistedRegistry, and an error, if there is any.
func (c *whitelistedRegistries) Update(ctx context.Context, whitelistedRegistry *v1.WhitelistedRegistry, opts metav1.UpdateOptions) (result *v1.WhitelistedRegistry, err error) {
	result = &v1.WhitelistedRegistry{}
	err = c.client.Put().
		Resource("whitelistedregistries").
		Name(whitelistedRegistry.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(whitelistedRegistry).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the whitelistedRegistry and deletes it. Returns an error if one occurs.
func (c *whitelistedRegistries) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("whitelistedregistries").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *whitelistedRegistries) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("whitelistedregistries").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched whitelistedRegistry.
func (c *whitelistedRegistries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.WhitelistedRegistry, err error) {
	result = &v1.WhitelistedRegistry{}
	err = c.client.Patch(pt).
		Resource("whitelistedregistries").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
