// Code generated by go-swagger; DO NOT EDIT.

package settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCurrentUserSettingsParams creates a new GetCurrentUserSettingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCurrentUserSettingsParams() *GetCurrentUserSettingsParams {
	return &GetCurrentUserSettingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCurrentUserSettingsParamsWithTimeout creates a new GetCurrentUserSettingsParams object
// with the ability to set a timeout on a request.
func NewGetCurrentUserSettingsParamsWithTimeout(timeout time.Duration) *GetCurrentUserSettingsParams {
	return &GetCurrentUserSettingsParams{
		timeout: timeout,
	}
}

// NewGetCurrentUserSettingsParamsWithContext creates a new GetCurrentUserSettingsParams object
// with the ability to set a context for a request.
func NewGetCurrentUserSettingsParamsWithContext(ctx context.Context) *GetCurrentUserSettingsParams {
	return &GetCurrentUserSettingsParams{
		Context: ctx,
	}
}

// NewGetCurrentUserSettingsParamsWithHTTPClient creates a new GetCurrentUserSettingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCurrentUserSettingsParamsWithHTTPClient(client *http.Client) *GetCurrentUserSettingsParams {
	return &GetCurrentUserSettingsParams{
		HTTPClient: client,
	}
}

/* GetCurrentUserSettingsParams contains all the parameters to send to the API endpoint
   for the get current user settings operation.

   Typically these are written to a http.Request.
*/
type GetCurrentUserSettingsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get current user settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserSettingsParams) WithDefaults() *GetCurrentUserSettingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get current user settings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCurrentUserSettingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get current user settings params
func (o *GetCurrentUserSettingsParams) WithTimeout(timeout time.Duration) *GetCurrentUserSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get current user settings params
func (o *GetCurrentUserSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get current user settings params
func (o *GetCurrentUserSettingsParams) WithContext(ctx context.Context) *GetCurrentUserSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get current user settings params
func (o *GetCurrentUserSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get current user settings params
func (o *GetCurrentUserSettingsParams) WithHTTPClient(client *http.Client) *GetCurrentUserSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get current user settings params
func (o *GetCurrentUserSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCurrentUserSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
