// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Chassis Chassis specifies the chassis info passed to the domain.
//
// swagger:model Chassis
type Chassis struct {

	// asset
	Asset string `json:"asset,omitempty"`

	// manufacturer
	Manufacturer string `json:"manufacturer,omitempty"`

	// serial
	Serial string `json:"serial,omitempty"`

	// sku
	Sku string `json:"sku,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this chassis
func (m *Chassis) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chassis based on context it is used
func (m *Chassis) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Chassis) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Chassis) UnmarshalBinary(b []byte) error {
	var res Chassis
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
