// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterTemplateOptions cluster template options
//
// swagger:model ClusterTemplateOptions
type ClusterTemplateOptions struct {

	// Predefined cluster template sizes
	Sizes []*ClusterTemplateSize `json:"clusterTemplateSizes"`
}

// Validate validates this cluster template options
func (m *ClusterTemplateOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSizes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterTemplateOptions) validateSizes(formats strfmt.Registry) error {
	if swag.IsZero(m.Sizes) { // not required
		return nil
	}

	for i := 0; i < len(m.Sizes); i++ {
		if swag.IsZero(m.Sizes[i]) { // not required
			continue
		}

		if m.Sizes[i] != nil {
			if err := m.Sizes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clusterTemplateSizes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this cluster template options based on the context it is used
func (m *ClusterTemplateOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSizes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ClusterTemplateOptions) contextValidateSizes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Sizes); i++ {

		if m.Sizes[i] != nil {
			if err := m.Sizes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("clusterTemplateSizes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ClusterTemplateOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterTemplateOptions) UnmarshalBinary(b []byte) error {
	var res ClusterTemplateOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
