// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContainerRuntimeContainerd ContainerRuntimeContainerd defines containerd container runtime registries configs.
//
// swagger:model ContainerRuntimeContainerd
type ContainerRuntimeContainerd struct {

	// A map of registries to use to render configs and mirrors for containerd registries
	Registries map[string]ContainerdRegistry `json:"registries,omitempty"`
}

// Validate validates this container runtime containerd
func (m *ContainerRuntimeContainerd) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegistries(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerRuntimeContainerd) validateRegistries(formats strfmt.Registry) error {
	if swag.IsZero(m.Registries) { // not required
		return nil
	}

	for k := range m.Registries {

		if err := validate.Required("registries"+"."+k, "body", m.Registries[k]); err != nil {
			return err
		}
		if val, ok := m.Registries[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("registries" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("registries" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this container runtime containerd based on the context it is used
func (m *ContainerRuntimeContainerd) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRegistries(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ContainerRuntimeContainerd) contextValidateRegistries(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Registries {

		if val, ok := m.Registries[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerRuntimeContainerd) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerRuntimeContainerd) UnmarshalBinary(b []byte) error {
	var res ContainerRuntimeContainerd
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
