// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EKSVPC EKSVPC represents a object of EKS VpcId.
//
// swagger:model EKSVPC
type EKSVPC struct {

	// ID
	ID string `json:"id,omitempty"`

	// is default
	IsDefault bool `json:"default,omitempty"`
}

// Validate validates this e k s v p c
func (m *EKSVPC) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e k s v p c based on context it is used
func (m *EKSVPC) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EKSVPC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EKSVPC) UnmarshalBinary(b []byte) error {
	var res EKSVPC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
