// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EKSSecurityGroup EKSSecurityGroup represents a object of EKS securityGroup.
//
// swagger:model EKSSecurityGroup
type EKSSecurityGroup struct {

	// The ID of the security group.
	GroupID string `json:"groupId,omitempty"`

	// [VPC only] The ID of the VPC for the security group.
	VpcID string `json:"vpcId,omitempty"`
}

// Validate validates this e k s security group
func (m *EKSSecurityGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e k s security group based on context it is used
func (m *EKSSecurityGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EKSSecurityGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EKSSecurityGroup) UnmarshalBinary(b []byte) error {
	var res EKSSecurityGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
