// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GCP g c p
//
// swagger:model GCP
type GCP struct {

	// If datacenter is set, this preset is only applicable to the
	// configured datacenter.
	Datacenter string `json:"datacenter,omitempty"`

	// Only enabled presets will be available in the KKP dashboard.
	Enabled bool `json:"enabled,omitempty"`

	// network
	Network string `json:"network,omitempty"`

	// service account
	ServiceAccount string `json:"serviceAccount,omitempty"`

	// subnetwork
	Subnetwork string `json:"subnetwork,omitempty"`
}

// Validate validates this g c p
func (m *GCP) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this g c p based on context it is used
func (m *GCP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GCP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GCP) UnmarshalBinary(b []byte) error {
	var res GCP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
