// Code generated by go-swagger; DO NOT EDIT.

package aks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/kubermatic/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListAKSVMSizesNoCredentialsReader is a Reader for the ListAKSVMSizesNoCredentials structure.
type ListAKSVMSizesNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAKSVMSizesNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAKSVMSizesNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListAKSVMSizesNoCredentialsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListAKSVMSizesNoCredentialsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewListAKSVMSizesNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListAKSVMSizesNoCredentialsOK creates a ListAKSVMSizesNoCredentialsOK with default headers values
func NewListAKSVMSizesNoCredentialsOK() *ListAKSVMSizesNoCredentialsOK {
	return &ListAKSVMSizesNoCredentialsOK{}
}

/* ListAKSVMSizesNoCredentialsOK describes a response with status code 200, with default header values.

AKSVMSizeList
*/
type ListAKSVMSizesNoCredentialsOK struct {
	Payload models.AKSVMSizeList
}

func (o *ListAKSVMSizesNoCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/providers/aks/vmsizes][%d] listAKSVmSizesNoCredentialsOK  %+v", 200, o.Payload)
}
func (o *ListAKSVMSizesNoCredentialsOK) GetPayload() models.AKSVMSizeList {
	return o.Payload
}

func (o *ListAKSVMSizesNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAKSVMSizesNoCredentialsUnauthorized creates a ListAKSVMSizesNoCredentialsUnauthorized with default headers values
func NewListAKSVMSizesNoCredentialsUnauthorized() *ListAKSVMSizesNoCredentialsUnauthorized {
	return &ListAKSVMSizesNoCredentialsUnauthorized{}
}

/* ListAKSVMSizesNoCredentialsUnauthorized describes a response with status code 401, with default header values.

EmptyResponse is a empty response
*/
type ListAKSVMSizesNoCredentialsUnauthorized struct {
}

func (o *ListAKSVMSizesNoCredentialsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/providers/aks/vmsizes][%d] listAKSVmSizesNoCredentialsUnauthorized ", 401)
}

func (o *ListAKSVMSizesNoCredentialsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListAKSVMSizesNoCredentialsForbidden creates a ListAKSVMSizesNoCredentialsForbidden with default headers values
func NewListAKSVMSizesNoCredentialsForbidden() *ListAKSVMSizesNoCredentialsForbidden {
	return &ListAKSVMSizesNoCredentialsForbidden{}
}

/* ListAKSVMSizesNoCredentialsForbidden describes a response with status code 403, with default header values.

EmptyResponse is a empty response
*/
type ListAKSVMSizesNoCredentialsForbidden struct {
}

func (o *ListAKSVMSizesNoCredentialsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/providers/aks/vmsizes][%d] listAKSVmSizesNoCredentialsForbidden ", 403)
}

func (o *ListAKSVMSizesNoCredentialsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListAKSVMSizesNoCredentialsDefault creates a ListAKSVMSizesNoCredentialsDefault with default headers values
func NewListAKSVMSizesNoCredentialsDefault(code int) *ListAKSVMSizesNoCredentialsDefault {
	return &ListAKSVMSizesNoCredentialsDefault{
		_statusCode: code,
	}
}

/* ListAKSVMSizesNoCredentialsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListAKSVMSizesNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list a k s VM sizes no credentials default response
func (o *ListAKSVMSizesNoCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *ListAKSVMSizesNoCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/projects/{project_id}/kubernetes/clusters/{cluster_id}/providers/aks/vmsizes][%d] listAKSVMSizesNoCredentials default  %+v", o._statusCode, o.Payload)
}
func (o *ListAKSVMSizesNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListAKSVMSizesNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
