// Code generated by go-swagger; DO NOT EDIT.

package nutanix

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/kubermatic/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListNutanixProjectsReader is a Reader for the ListNutanixProjects structure.
type ListNutanixProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNutanixProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNutanixProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListNutanixProjectsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListNutanixProjectsOK creates a ListNutanixProjectsOK with default headers values
func NewListNutanixProjectsOK() *ListNutanixProjectsOK {
	return &ListNutanixProjectsOK{}
}

/* ListNutanixProjectsOK describes a response with status code 200, with default header values.

NutanixProjectList
*/
type ListNutanixProjectsOK struct {
	Payload models.NutanixProjectList
}

func (o *ListNutanixProjectsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/projects][%d] listNutanixProjectsOK  %+v", 200, o.Payload)
}
func (o *ListNutanixProjectsOK) GetPayload() models.NutanixProjectList {
	return o.Payload
}

func (o *ListNutanixProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNutanixProjectsDefault creates a ListNutanixProjectsDefault with default headers values
func NewListNutanixProjectsDefault(code int) *ListNutanixProjectsDefault {
	return &ListNutanixProjectsDefault{
		_statusCode: code,
	}
}

/* ListNutanixProjectsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListNutanixProjectsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list nutanix projects default response
func (o *ListNutanixProjectsDefault) Code() int {
	return o._statusCode
}

func (o *ListNutanixProjectsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/projects][%d] listNutanixProjects default  %+v", o._statusCode, o.Payload)
}
func (o *ListNutanixProjectsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListNutanixProjectsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
