// Code generated by go-swagger; DO NOT EDIT.

package nutanix

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"k8c.io/kubermatic/v2/pkg/test/e2e/utils/apiclient/models"
)

// ListNutanixSubnetsReader is a Reader for the ListNutanixSubnets structure.
type ListNutanixSubnetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNutanixSubnetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNutanixSubnetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListNutanixSubnetsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListNutanixSubnetsOK creates a ListNutanixSubnetsOK with default headers values
func NewListNutanixSubnetsOK() *ListNutanixSubnetsOK {
	return &ListNutanixSubnetsOK{}
}

/*
ListNutanixSubnetsOK describes a response with status code 200, with default header values.

NutanixSubnetList
*/
type ListNutanixSubnetsOK struct {
	Payload models.NutanixSubnetList
}

// IsSuccess returns true when this list nutanix subnets o k response has a 2xx status code
func (o *ListNutanixSubnetsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list nutanix subnets o k response has a 3xx status code
func (o *ListNutanixSubnetsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list nutanix subnets o k response has a 4xx status code
func (o *ListNutanixSubnetsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list nutanix subnets o k response has a 5xx status code
func (o *ListNutanixSubnetsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list nutanix subnets o k response a status code equal to that given
func (o *ListNutanixSubnetsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListNutanixSubnetsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/subnets][%d] listNutanixSubnetsOK  %+v", 200, o.Payload)
}

func (o *ListNutanixSubnetsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/subnets][%d] listNutanixSubnetsOK  %+v", 200, o.Payload)
}

func (o *ListNutanixSubnetsOK) GetPayload() models.NutanixSubnetList {
	return o.Payload
}

func (o *ListNutanixSubnetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNutanixSubnetsDefault creates a ListNutanixSubnetsDefault with default headers values
func NewListNutanixSubnetsDefault(code int) *ListNutanixSubnetsDefault {
	return &ListNutanixSubnetsDefault{
		_statusCode: code,
	}
}

/*
ListNutanixSubnetsDefault describes a response with status code -1, with default header values.

errorResponse
*/
type ListNutanixSubnetsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list nutanix subnets default response
func (o *ListNutanixSubnetsDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this list nutanix subnets default response has a 2xx status code
func (o *ListNutanixSubnetsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list nutanix subnets default response has a 3xx status code
func (o *ListNutanixSubnetsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list nutanix subnets default response has a 4xx status code
func (o *ListNutanixSubnetsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list nutanix subnets default response has a 5xx status code
func (o *ListNutanixSubnetsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list nutanix subnets default response a status code equal to that given
func (o *ListNutanixSubnetsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *ListNutanixSubnetsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/subnets][%d] listNutanixSubnets default  %+v", o._statusCode, o.Payload)
}

func (o *ListNutanixSubnetsDefault) String() string {
	return fmt.Sprintf("[GET /api/v2/providers/nutanix/{dc}/subnets][%d] listNutanixSubnets default  %+v", o._statusCode, o.Payload)
}

func (o *ListNutanixSubnetsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListNutanixSubnetsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
