// Code generated by go-swagger; DO NOT EDIT.

package nutanix

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListNutanixCategoryValuesNoCredentialsParams creates a new ListNutanixCategoryValuesNoCredentialsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListNutanixCategoryValuesNoCredentialsParams() *ListNutanixCategoryValuesNoCredentialsParams {
	return &ListNutanixCategoryValuesNoCredentialsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListNutanixCategoryValuesNoCredentialsParamsWithTimeout creates a new ListNutanixCategoryValuesNoCredentialsParams object
// with the ability to set a timeout on a request.
func NewListNutanixCategoryValuesNoCredentialsParamsWithTimeout(timeout time.Duration) *ListNutanixCategoryValuesNoCredentialsParams {
	return &ListNutanixCategoryValuesNoCredentialsParams{
		timeout: timeout,
	}
}

// NewListNutanixCategoryValuesNoCredentialsParamsWithContext creates a new ListNutanixCategoryValuesNoCredentialsParams object
// with the ability to set a context for a request.
func NewListNutanixCategoryValuesNoCredentialsParamsWithContext(ctx context.Context) *ListNutanixCategoryValuesNoCredentialsParams {
	return &ListNutanixCategoryValuesNoCredentialsParams{
		Context: ctx,
	}
}

// NewListNutanixCategoryValuesNoCredentialsParamsWithHTTPClient creates a new ListNutanixCategoryValuesNoCredentialsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListNutanixCategoryValuesNoCredentialsParamsWithHTTPClient(client *http.Client) *ListNutanixCategoryValuesNoCredentialsParams {
	return &ListNutanixCategoryValuesNoCredentialsParams{
		HTTPClient: client,
	}
}

/*
ListNutanixCategoryValuesNoCredentialsParams contains all the parameters to send to the API endpoint

	for the list nutanix category values no credentials operation.

	Typically these are written to a http.Request.
*/
type ListNutanixCategoryValuesNoCredentialsParams struct {

	/* Category.

	   Category to query the available values for
	*/
	Category string

	// ClusterID.
	ClusterID string

	// ProjectID.
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list nutanix category values no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithDefaults() *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list nutanix category values no credentials params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithTimeout(timeout time.Duration) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithContext(ctx context.Context) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithHTTPClient(client *http.Client) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCategory adds the category to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithCategory(category string) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetCategory(category)
	return o
}

// SetCategory adds the category to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetCategory(category string) {
	o.Category = category
}

// WithClusterID adds the clusterID to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithClusterID(clusterID string) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithProjectID adds the projectID to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) WithProjectID(projectID string) *ListNutanixCategoryValuesNoCredentialsParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the list nutanix category values no credentials params
func (o *ListNutanixCategoryValuesNoCredentialsParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *ListNutanixCategoryValuesNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param category
	if err := r.SetPathParam("category", o.Category); err != nil {
		return err
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
