// Code generated by go-swagger; DO NOT EDIT.

package gcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListGCPNetworksNoCredentialsParams creates a new ListGCPNetworksNoCredentialsParams object
// with the default values initialized.
func NewListGCPNetworksNoCredentialsParams() *ListGCPNetworksNoCredentialsParams {

	return &ListGCPNetworksNoCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListGCPNetworksNoCredentialsParamsWithTimeout creates a new ListGCPNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListGCPNetworksNoCredentialsParamsWithTimeout(timeout time.Duration) *ListGCPNetworksNoCredentialsParams {

	return &ListGCPNetworksNoCredentialsParams{

		timeout: timeout,
	}
}

// NewListGCPNetworksNoCredentialsParamsWithContext creates a new ListGCPNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListGCPNetworksNoCredentialsParamsWithContext(ctx context.Context) *ListGCPNetworksNoCredentialsParams {

	return &ListGCPNetworksNoCredentialsParams{

		Context: ctx,
	}
}

// NewListGCPNetworksNoCredentialsParamsWithHTTPClient creates a new ListGCPNetworksNoCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListGCPNetworksNoCredentialsParamsWithHTTPClient(client *http.Client) *ListGCPNetworksNoCredentialsParams {

	return &ListGCPNetworksNoCredentialsParams{
		HTTPClient: client,
	}
}

/*ListGCPNetworksNoCredentialsParams contains all the parameters to send to the API endpoint
for the list g c p networks no credentials operation typically these are written to a http.Request
*/
type ListGCPNetworksNoCredentialsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) WithTimeout(timeout time.Duration) *ListGCPNetworksNoCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) WithContext(ctx context.Context) *ListGCPNetworksNoCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) WithHTTPClient(client *http.Client) *ListGCPNetworksNoCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list g c p networks no credentials params
func (o *ListGCPNetworksNoCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListGCPNetworksNoCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
