/*
Copyright 2026 The Kubermatic Kubernetes Platform contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/sirupsen/logrus"
)

const (
	limaVMNamePrefix    = "kkp-"
	limaRegistryPort    = 5000
	vmKindAPIserverPort = 36443
	vmKindVersion       = "v0.27.0"
	vmRemoteDir         = "/tmp/kkp-local"
)

type limaVM struct {
	instance string
	cluster  string
	ip       string
}

func limaVMName(clusterName string) string {
	return limaVMNamePrefix + clusterName
}

// limaVMTemplate renders the lima instance template for a local kind VM.
// Plain (default) lima networking is used; the in-VM registry, the kind
// apiserver and the four KKP host ports are forwarded 1:1 between host
// and guest, so the same port numbers work on both sides.
func limaVMTemplate(clusterName string, cpus, memory, disk int, hostPorts map[string]int) string {
	ports := defaultLocalHostPorts()
	for key, value := range hostPorts {
		ports[key] = value
	}

	forwards := ""
	for _, forward := range []struct {
		port    int
		comment string
	}{
		{limaRegistryPort, "local container registry"},
		{vmKindAPIserverPort, "kind apiserver"},
		{ports["http"], "envoy gateway http"},
		{ports["https"], "envoy gateway https"},
		{ports["apiserver"], "nodeport-proxy apiserver tunnel"},
		{ports["tunnel"], "nodeport-proxy tunnel listener"},
	} {
		forwards += fmt.Sprintf("# %s\n- guestPort: %d\n  hostPort: %d\n", forward.comment, forward.port, forward.port)
	}

	return fmt.Sprintf(`# generated by kubermatic-installer local kind --vm
# instance: %s (reuse an existing VM with: limactl start %s)
cpus: %d
memory: "%dGiB"
disk: "%dGiB"
portForwards:
%s`, limaVMName(clusterName), limaVMName(clusterName), cpus, memory, disk, forwards)
}

func limaCommand(ctx context.Context, args ...string) *exec.Cmd {
	return exec.CommandContext(ctx, "limactl", append([]string{"--tty=false"}, args...)...)
}

func (vm *limaVM) shell(ctx context.Context, args ...string) *exec.Cmd {
	return limaCommand(ctx, append([]string{"shell", vm.instance, "--"}, args...)...)
}

func limaVMExists(ctx context.Context, instance string) bool {
	out, err := limaCommand(ctx, "list", "--quiet", instance).Output()
	if err != nil {
		return false
	}
	for _, line := range strings.Fields(string(out)) {
		if line == instance {
			return true
		}
	}
	return false
}

func startLimaVM(ctx context.Context, logger *logrus.Logger, opt *LocalOptions) (*limaVM, error) {
	instance := limaVMName(opt.ClusterName)

	if limaVMExists(ctx, instance) {
		logger.Infof("Lima VM %q already exists, reusing it (--vm-cpus, --vm-memory, --vm-disk and --host-ports changes are ignored)", instance)
		logger.Infof("Starting lima VM %q…", instance)
		if out, err := limaCommand(ctx, "start", instance).CombinedOutput(); err != nil {
			return nil, fmt.Errorf("failed to start lima VM %q: %w\n%s", instance, err, string(out))
		}
	} else {
		templateDir, err := os.MkdirTemp("", "kkp-lima-")
		if err != nil {
			return nil, fmt.Errorf("failed to create temporary directory for the lima template: %w", err)
		}
		defer os.RemoveAll(templateDir)

		template := filepath.Join(templateDir, "lima-vm.yaml")
		if err := os.WriteFile(template, []byte(limaVMTemplate(opt.ClusterName, opt.VMCPUs, opt.VMMemory, opt.VMDisk, opt.HostPorts)), 0644); err != nil {
			return nil, fmt.Errorf("failed to write lima template: %w", err)
		}

		logger.Infof("Creating lima VM %q (%d CPUs, %d GiB memory, %d GiB disk)…", instance, opt.VMCPUs, opt.VMMemory, opt.VMDisk)
		if out, err := limaCommand(ctx, "start", "--name", instance, template).CombinedOutput(); err != nil {
			return nil, fmt.Errorf("failed to create lima VM %q: %w\n%s", instance, err, string(out))
		}
	}

	return &limaVM{
		instance: instance,
		cluster:  opt.ClusterName,
	}, nil
}
